# Zadanie 5: programowanie genetyczne i regresja symboliczna

Termin realizacji: 18 maja 2026

Zadanie do oddania przez MS Teams. Do oddania: kod oraz krótkie sprawozdanie w PDF (można na przykład przy użyciu `quarto render notebook.ipynb --to pdf`).

## Na 3.0

Do realizacji:

1. Zmodyfikuj przykład `pysr_demo.ipynb` tak, aby uczył się funkcji $f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$ której dziedziną jest $\mathbb{R}^6$. Uczenie ma się odbywać w oparciu o 200 wylosowanych z dziedziny próbek (między -5 a 5).
2. Zanotuj wzory trzech rozwiązań o najwyższej wartości `score` oraz rozwiązanie `best` dla następujących zestawów ustawień:
   1. `binary_operators=["+", "*"], unary_operators=["cos", "exp", "sin"], maxsize=20`,
   2. `binary_operators=["+", "*", "-", "^"], unary_operators=["cos", "exp", "sin", "log"], maxsize=30`, (dodaj ograniczenie dla argumentów operatora "^": [https://astroautomata.com/PySR/v1.5.9/operators#custom](https://astroautomata.com/PySR/v1.5.9/operators#custom) ).
   3. `binary_operators=["+", "*", "-", "^"], unary_operators=["exp", "sin"], maxsize=15`.
3. Powtórz eksperymenty z zadania na 3.0 po dodaniu szumu do próbek z funkcji $f$ (rozkład normalny o średniej 0 i odchyleniu standardowym 0.5)

## Na 4.0

Do realizacji:

1. Punkty z zadania na 3.0.
2. Dodaj do porównania dopasowanie oparte o próbki losowane w szerszym zakresie (między -15 a 15) oraz wyższy poziom szumu (odchylenie standardowe równe 2 oraz 5).

## Na 5.0

Do realizacji:

1. Punkty z zadania na 4.0.
2. Zamień funkcję $f$ na $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$ gdzie $p(i)$ oznacza $i$-tą liczbę pierwszą. Uwzględnij `p` jako dodatkowy operator unarny analogicznie do przykładu "Julia packages and types" z notatnika `pysr_demo.ipynb`. Powtórz eksperymenty opisane w zadaniach na 3.0 i 4.0.

## Importy

In [1]:
import numpy as np
import sympy
from pysr import PySRRegressor

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

In [2]:
default_pysr_params = dict(
    populations=50,
    model_selection="best",
    niterations=100,
)

In [3]:
SAFE_POW = "safe_pow(x, y) = (x >= 0 || isinteger(y)) ? x ^ y : convert(typeof(x), NaN)"
safe_pow_sympy = {"safe_pow": lambda x, y: x**y}

## Funkcja pomocnicza do wyświetlania wyników

In [4]:
def show_results(model):
    display(model.equations_.nlargest(3, 'score')[['complexity', 'loss', 'score', 'equation']])
    print('best:', model.sympy())

## 3.0 — Dane bez szumu, zakres [-5, 5]

Funkcja: $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - 3$, dziedzina $\mathbb{R}^6$, 200 próbek.

In [5]:
np.random.seed(0)
X = np.random.uniform(-5, 5, (200, 6))
y = 2.2 * np.sin(X[:, 0] + 2 * X[:, 1]) - X[:, 5]**2 - 3

### Konfiguracja 1 — `binary=["+","*"]`, `unary=["cos","exp","sin"]`, `maxsize=20`

In [6]:
model1 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1.fit(X, y)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
Compiling Julia backend...
[ Info: Started!

Expressions evaluated per second: 6.390e+05
Progress: 3515 / 5000 total iterations (70.300%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.158
3           5.546e+01  1.239e-03  y = x₂ + -11.311
4           5.152e+01  7.370e-02  y = cos(x₅) + -10.987
5           6.759e+00  2.031e+00  y = (x₅ * -1.1932) * x₅
7           2.205e+00  5.600e-01  y = (x₅ * (x₅ * -0.98155)) + -3.163
9           2.197e+00  1.884e-03  y = ((x₅ + 0.033224) * (x₅ * -0.9792)) + -3.1777
11          2.173e+00  5.516e-03  y = (x₀ * 0.059189) + (((x₅ * x₅) * -0.98035) + -3.1557)
12          2.106e+00  3.128e-02  y = ((sin(x₀) * -0.43337) + ((x₅ * x₅) * -0.97735)) + -3.1...
                                      968
13          2.050e+00  2.710e-02  y = ((x₅ * (x₅ * -0.97888)) + -3.084) + cos(cos(x₁) + x₁)
14          1.965e+00  4.233e-02  y = (((x₅ * -0.98246) * x₅) + -3.9483) + cos(cos(x₁ + cos(...
                                      x₀)))
15          1.749e+00  1.165e-01  y = (((x₅ * -0.98634) * x₅) + -3.2905) + cos(cos(x₁ + 2.44...
                                      16) * x₀)
16          1.504e+00  1.507e-01  y = ((x₅ * (x₅ * -0.98637)) + (cos(cos(cos(x₀) + x₁)) * 5....
                                      2777)) + -7.3069
17          1.473e+00  2.079e-02  y = (cos(cos(x₁ + sin(cos(x₀)))) * 5.4479) + (((x₅ * -0.98...
                                      844) * x₅) + -7.4518)
18          1.247e+00  1.666e-01  y = (((x₅ * -0.98356) * x₅) + cos((x₁ + exp(cos(exp(sin(x₁...
                                      ))))) + x₀)) + -3.0831
19          1.227e+00  1.625e-02  y = (cos(cos(cos(x₁) * -2.3242) + sin(x₀)) + (((x₅ * -0.40...
                                      177) * x₅) + -1.8177)) * 2.4716
20          8.615e-01  3.535e-01  y = (cos(cos(x₁ + (exp(sin(x₀)) * cos(x₀)))) * 7.36) + (((...
                                      x₅ * -0.99908) * x₅) + -8.7293)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.158
3           5.546e+01  1.239e-03  y = x₂ + -11.311
4           5.152e+01  7.370e-02  y = cos(x₅) + -10.987
5           6.759e+00  2.031e+00  y = (x₅ * -1.1932) * x₅
7           2.205e+00  5.600e-01  y = (x₅ * (x₅ * -0.98155)) + -3.163
9           2.197e+00  1.884e-03  y = ((x₅ + 0.033224) * (x₅ * -0.9792)) + -3.1777
11          2.173e+00  5.516e-03  y = (x₀ * 0.059189) + (((x₅ * x₅) * -0.98035) + -3.1557)
12          2.106e+00  3.128e-02  y = ((sin(x₀) * -0.43337) + ((x₅ * x₅) * -0.97735)) + -3.1...
                                      968
13          2.050e+00  2.710e-02  y = ((x₅ * (x₅ * -0.97888)) + -3.084) + cos(cos(x₁) + x₁)
14          1.965e+00  4.233e-02  y = (((x₅ * -0.98246) * x₅) + -3.9483) + cos(cos(x₁ + cos(...
                                      x₀)))
15          1.749e+00  1.165e-01  y = (((x₅ * -0.98634) * x₅) + -3.2905) + cos(cos(x₁ + 2.44...
                                      16) * x₀)
16          1.504e+00  1.507e-01  y = ((x₅ * (x₅ * -0.98637)) + (cos(cos(cos(x₀) + x₁)) * 5....
                                      2777)) + -7.3069
17          1.473e+00  2.079e-02  y = (cos(cos(x₁ + sin(cos(x₀)))) * 5.4479) + (((x₅ * -0.98...
                                      844) * x₅) + -7.4518)
18          1.247e+00  1.666e-01  y = (((x₅ * -0.98356) * x₅) + cos((x₁ + exp(cos(exp(sin(x₁...
                                      ))))) + x₀)) + -3.0831
19          9.554e-01  2.664e-01  y = (cos(cos((exp(sin(x₀)) * -0.61585) + x₁)) * 6.8844) + ...
                                      (-8.2798 + ((x₅ * -0.99212) * x₅))
20          8.615e-01  1.034e-01  y = (cos(cos(x₁ + (exp(sin(x₀)) * cos(x₀)))) * 7.36) + (((...
                                      x₅ * -0.99908) * x₅) + -8.7293)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_142956_w6Jztd/hall_of_fame.csv

In [7]:
show_results(model1)

,complexity,loss,score,equation
3,5,6.758767,2.031154,(x5 * -1.1931673) * x5
4,7,2.205166,0.560019,(x5 * (x5 * -0.9815521)) + -3.1630116
14,19,0.955366,0.266378,(cos(cos((exp(sin(x0)) * -0.61584556) + x1)) *...

best: x5*(-0.99212056)*x5 + cos(cos(x1 + exp(sin(x0))*(-0.61584556)))*6.8843594 - 8.279847

### Konfiguracja 2 — `binary=["+","*","-","^"]`, `unary=["cos","exp","sin","log"]`, `maxsize=30`

Ograniczenie dla `^`: prawy argument ma maksymalną złożoność 1.

In [8]:
model2 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model2.fit(X, y)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

Expressions evaluated per second: 4.150e+05
Progress: 2299 / 5000 total iterations (45.980%)
════════════════════════════════════════════════════════════════════════════════════════════════════

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.158
3           5.537e+01  2.049e-03  y = -11.021 - x₅
4           5.152e+01  7.208e-02  y = cos(x₅) + -10.987
5           2.224e+00  3.143e+00  y = -3.0128 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * x₅) - -3.2223) * -0.98156
9           2.153e+00  1.189e-02  y = (x₅ * ((x₄ * 0.03329) - x₅)) - 3.0191
10          2.134e+00  9.020e-03  y = (-3.0123 - (x₅ * x₅)) - (sin(x₀) * 0.41059)
11          2.074e+00  2.840e-02  y = (-2.912 - (x₅ * x₅)) + cos(cos(x₁) + x₁)
12          6.617e-01  1.143e+00  y = (sin((x₁ + x₁) + x₀) - 3.007) - (x₅ * x₅)
14          6.561e-01  4.262e-03  y = (sin(x₁ + (x₁ + x₀)) + -3.089) - ((x₅ * 0.98993) * x₅)
16          8.505e-13  1.369e+01  y = ((cos((x₁ + x₁) + (x₀ + -1.5708)) * 2.2) + -3) - (x₅ *...
                                       x₅)
20          7.041e-13  4.722e-02  y = (-3 - ((x₁ + (x₅ * x₅)) - x₁)) + (cos((x₀ + -1.5708) +...
                                       (x₁ + x₁)) * 2.2)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.158
3           5.537e+01  2.049e-03  y = -11.021 - x₅
4           5.152e+01  7.208e-02  y = cos(x₅) + -10.987
5           2.224e+00  3.143e+00  y = -3.0129 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * x₅) - -3.2223) * -0.98156
9           2.153e+00  1.189e-02  y = (x₅ * ((x₄ * 0.03329) - x₅)) - 3.0191
10          2.106e+00  2.231e-02  y = (-3.0706 - (x₅ * x₅)) - sin(x₁ * 2.0612)
11          2.074e+00  1.511e-02  y = (-2.912 - (x₅ * x₅)) + cos(cos(x₁) + x₁)
12          6.617e-01  1.143e+00  y = (sin((x₀ + x₁) + x₁) - 3.007) - (x₅ * x₅)
13          5.724e-01  1.449e-01  y = (exp(sin(x₀ + (x₁ + x₁))) - (x₅ * x₅)) + -4.2498
14          8.464e-13  2.724e+01  y = ((sin((x₁ + x₁) + x₀) * 2.2) - (x₅ * x₅)) + -3
16          7.154e-13  8.404e-02  y = (cos((x₁ + x₁) + (x₀ + -1.5708)) * 2.2) + (-3 - (x₅ * ...
                                      x₅))
20          6.933e-13  7.869e-03  y = (cos((x₀ + -1.5708) + (x₁ + x₁)) * 2.2) + (-3 - ((x₁ +...
                                       (x₅ * x₅)) - x₁))
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143009_YLJBt8/hall_of_fame.csv

In [9]:
show_results(model2)

,complexity,loss,score,equation
10,14,8.463985e-13,27.239924,((sin((x1 + x1) + x0) * 2.2) - (x5 * x5)) + -3...
3,5,2.224043e+00,3.142667,-3.0129461 - (x5 * x5)
8,12,6.616987e-01,1.142550,(sin((x0 + x1) + x1) - 3.0070133) - (x5 * x5)

best: -x5*x5 + sin(x0 + x1 + x1)*2.2 - 3.0000002

### Konfiguracja 3 — `binary=["+","*","-","^"]`, `unary=["exp","sin"]`, `maxsize=15`

In [10]:
model3 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model3.fit(X, y)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.158
3           5.537e+01  2.049e-03  y = -11.021 - x₅
4           5.462e+01  1.364e-02  y = -11.157 - sin(x₀)
5           2.224e+00  3.201e+00  y = -3.0129 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * -0.98154) * x₅) - 3.1631
9           2.153e+00  1.189e-02  y = -3.0191 - (x₅ * (x₅ + (x₄ * -0.03329)))
10          2.106e+00  2.231e-02  y = (sin(x₁ * -2.0613) + -3.0706) - (x₅ * x₅)
11          2.067e+00  1.866e-02  y = -3.0645 - (sin(sin(x₁ * 2.0553)) + (x₅ * x₅))
12          6.617e-01  1.139e+00  y = (sin(x₁ + (x₀ + x₁)) + -3.007) - (x₅ * x₅)
13          5.722e-01  1.452e-01  y = exp(sin(x₀ + (x₁ * 1.9959))) + (-4.2504 - (x₅ * x₅))
14          8.464e-13  2.724e+01  y = ((sin((x₁ + x₁) + x₀) * 2.2) - (x₅ * x₅)) + -3
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143019_O2Ef4k/hall_of_fame.csv

In [11]:
show_results(model3)

,complexity,loss,score,equation
10,14,8.463985e-13,27.239601,((sin((x1 + x1) + x0) * 2.2) - (x5 * x5)) + -3...
3,5,2.224043e+00,3.201109,-3.0128849 - (x5 * x5)
8,12,6.616987e-01,1.138992,(sin(x1 + (x0 + x1)) + -3.0070133) - (x5 * x5)

best: -x5*x5 + sin(x0 + x1 + x1)*2.2 - 3.0000002

## 3.0 — Dane z szumem $\mathcal{N}(0,\,0.5^2)$, zakres [-5, 5]

In [12]:
np.random.seed(0)
X_n05 = np.random.uniform(-5, 5, (200, 6))
y_n05 = 2.2 * np.sin(X_n05[:, 0] + 2 * X_n05[:, 1]) - X_n05[:, 5]**2 - 3 + np.random.normal(0, 0.5, 200)

### Konfiguracja 1 (szum 0.5)

In [13]:
model1_n05 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1_n05.fit(X_n05, y_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 7.910e+05
Progress: 4329 / 5000 total iterations (86.580%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.092
3           5.560e+01  5.008e-04  y = x₂ + -11.246
4           5.159e+01  7.493e-02  y = cos(x₅) + -10.922
5           6.855e+00  2.018e+00  y = (x₅ * -1.188) * x₅
7           2.449e+00  5.148e-01  y = (x₅ * (x₅ * -0.97982)) + -3.1117
9           2.434e+00  2.937e-03  y = (x₅ * ((x₅ * -0.97674) + -0.042771)) + -3.1309
11          2.363e+00  1.485e-02  y = (x₅ * ((x₅ * -0.97839) + (x₄ * 0.036652))) + -3.1303
12          2.332e+00  1.324e-02  y = ((sin(x₁ * 2.0193) + (x₅ * x₅)) * -0.97759) + -3.1949
13          2.292e+00  1.707e-02  y = (((x₅ * x₅) + sin(sin(x₁ * 2.0148))) * -0.97868) + -3....
                                      179
14          8.827e-01  9.543e-01  y = sin(x₀ + (x₁ * 1.9838)) + ((x₅ * (x₅ * -0.98872)) + -3...
                                      .0356)
16          2.035e-01  7.338e-01  y = (((x₅ * -0.99979) * x₅) + (sin(x₀ + (x₁ * 1.9807)) * 2...
                                      .2227)) + -2.9418
18          2.025e-01  2.270e-03  y = ((sin((x₁ * 1.9806) + x₀) * 2.2201) + (((x₅ + 0.010875...
                                      ) * -0.999) * x₅)) + -2.9468
20          2.022e-01  9.095e-04  y = ((sin((x₁ + (x₀ + x₁)) * 0.99127) * 2.221) + -2.9558) ...
                                      + (((x₅ + 0.0096069) * x₅) * -0.99866)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.092
3           5.560e+01  5.008e-04  y = x₂ + -11.246
4           5.159e+01  7.493e-02  y = cos(x₅) + -10.922
5           6.855e+00  2.018e+00  y = (x₅ * -1.188) * x₅
7           2.449e+00  5.148e-01  y = (x₅ * (x₅ * -0.97982)) + -3.1117
9           2.434e+00  2.937e-03  y = (x₅ * ((x₅ * -0.97674) + -0.042771)) + -3.1309
11          2.363e+00  1.485e-02  y = (x₅ * ((x₅ * -0.97839) + (x₄ * 0.036652))) + -3.1303
12          2.332e+00  1.324e-02  y = ((sin(x₁ * 2.0193) + (x₅ * x₅)) * -0.97759) + -3.1949
13          2.292e+00  1.707e-02  y = (((x₅ * x₅) + sin(sin(x₁ * 2.0148))) * -0.97868) + -3....
                                      179
14          8.827e-01  9.543e-01  y = sin(x₀ + (x₁ * 1.9838)) + ((x₅ * (x₅ * -0.98872)) + -3...
                                      .0356)
15          7.924e-01  1.080e-01  y = (exp(sin(x₀ + (x₁ * 1.9764))) + ((x₅ * x₅) * -0.99071)...
                                      ) + -4.2634
16          2.035e-01  1.360e+00  y = ((x₅ * (x₅ * -0.99979)) + (sin((x₁ * 1.9807) + x₀) * 2...
                                      .2228)) + -2.9419
18          2.025e-01  2.270e-03  y = ((sin((x₁ * 1.9806) + x₀) * 2.2201) + (((x₅ + 0.010875...
                                      ) * -0.999) * x₅)) + -2.9468
20          2.022e-01  9.095e-04  y = ((sin((x₁ + (x₀ + x₁)) * 0.99127) * 2.221) + -2.9558) ...
                                      + (((x₅ + 0.0096069) * x₅) * -0.99866)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143025_4pHJR9/hall_of_fame.csv

In [14]:
show_results(model1_n05)

,complexity,loss,score,equation
3,5,6.855120,2.018258,(x5 * -1.1879798) * x5
11,16,0.203464,1.359571,((x5 * (x5 * -0.9997855)) + (sin((x1 * 1.98074...
9,14,0.882724,0.954339,sin(x0 + (x1 * 1.9837806)) + ((x5 * (x5 * -0.9...

best: x5*x5*(-0.9997855) + sin(x0 + x1*1.980745)*2.2228205 - 2.9419146

### Konfiguracja 2 (szum 0.5)

In [15]:
model2_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model2_n05.fit(X_n05, y_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 5.260e+05
Progress: 2868 / 5000 total iterations (57.360%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.093
3           5.528e+01  3.373e-03  y = -10.955 - x₅
4           5.159e+01  6.919e-02  y = cos(x₅) + -10.922
5           2.471e+00  3.039e+00  y = -2.9475 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = (x₅ * (x₅ * -0.97982)) + -3.1117
9           2.389e+00  1.235e-02  y = (((x₄ * 0.035916) - x₅) * x₅) + -2.9541
10          2.360e+00  1.222e-02  y = -3.0128 - (sin(x₁ * 2.025) + (x₅ * x₅))
11          2.292e+00  2.917e-02  y = (-2.9825 - (x₅ * x₅)) - (sin(x₁) * cos(x₁))
12          8.897e-01  9.462e-01  y = (-2.9439 - (x₅ * x₅)) - sin((x₁ * -1.9819) - x₀)
14          2.035e-01  7.377e-01  y = (-2.9403 - (x₅ * x₅)) - (sin((x₁ * -1.9809) - x₀) * 2....
                                      2225)
16          2.026e-01  2.148e-03  y = (((-0.010356 - x₅) * x₅) - (sin((x₁ * -1.9804) - x₀) *...
                                       2.2212)) + -2.9388
18          2.025e-01  2.372e-04  y = ((x₅ * (-0.010464 - x₅)) - (sin((x₁ * -1.9806) + (-0.0...
                                      060566 - x₀)) * 2.2206)) + -2.9392
20          2.019e-01  1.478e-03  y = (((-0.0095801 - x₅) * x₅) + -3.0401) + ((0.043726 - si...
                                      n((x₁ * -1.9806) - (x₀ * 0.99468))) * 2.2222)
22          2.019e-01  1.176e-04  y = ((-0.0096744 - x₅) * x₅) + ((sin(0.012177 - (((x₁ * -1...
                                      .9807) + 0.0078991) - (x₀ * 0.99483))) * 2.2218) + -2.943)
24          2.019e-01  1.788e-07  y = (((x₅ + (x₅ * (-1.0097 - x₅))) + -2.9891) - (sin(-0.00...
                                      42636 + ((x₁ * -1.9807) - (x₀ * 0.99484))) * 2.2218)) - -0...
                                      .046055
26          2.005e-01  3.488e-03  y = ((((-0.012003 - x₅) * x₅) + -2.9407) - sin(sin((x₁ * -...
                                      2.074) + (-0.0059192 - x₀)))) - (sin((x₁ * -1.9225) - x₀) ...
                                      * 1.3972)
27          1.998e-01  3.116e-03  y = ((((-0.012852 - x₅) * x₅) + -2.9411) - sin(sin(sin((0....
                                      033899 - x₀) + (x₁ * -2.0922))))) - (sin((x₁ * -1.9218) - ...
                                      x₀) * 1.4916)
29          1.991e-01  1.832e-03  y = ((((-0.012852 - x₅) * x₅) + -2.9411) - sin(sin(sin((0....
                                      033899 - x₀) + (x₁ * -2.0922))))) - (sin(((x₁ * -1.9218) +...
                                       -0.024738) - x₀) * 1.4916)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.093
3           5.528e+01  3.373e-03  y = -10.955 - x₅
4           5.159e+01  6.919e-02  y = cos(x₅) + -10.922
5           2.471e+00  3.039e+00  y = -2.9475 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = (x₅ * (x₅ * -0.97982)) + -3.1117
9           2.389e+00  1.235e-02  y = (((x₄ * 0.035916) - x₅) * x₅) + -2.9541
10          2.360e+00  1.222e-02  y = (-3.0128 - (x₅ * x₅)) - sin(x₁ * 2.025)
11          2.292e+00  2.917e-02  y = (-2.9825 - (x₅ * x₅)) - (sin(x₁) * cos(x₁))
12          8.897e-01  9.462e-01  y = (-2.9439 - (x₅ * x₅)) - sin((x₁ * -1.9819) - x₀)
14          2.035e-01  7.377e-01  y = (-2.9401 - (x₅ * x₅)) - (sin((x₁ * -1.9807) - x₀) * 2....
                                      2229)
16          2.026e-01  2.145e-03  y = (-2.9388 + ((-0.010356 - x₅) * x₅)) - (sin((x₁ * -1.98...
                                      04) - x₀) * 2.2212)
18          2.019e-01  1.715e-03  y = ((-0.0095788 - x₅) * x₅) + (-2.9429 - (sin(((-1.9912 *...
                                       x₁) - x₀) * -0.99468) * -2.2223))
19          2.000e-01  9.710e-03  y = (-2.9552 - (cos(x₂) * 0.089976)) - ((x₅ * x₅) - (sin((...
                                      x₁ * -1.9805) - x₀) * -2.2294))
20          1.984e-01  7.618e-03  y = ((-2.9217 - (sin(exp(x₀)) * 0.15182)) - (x₅ * x₅)) - (...
                                      2.2305 * sin((x₁ * -1.9797) - x₀))
21          1.972e-01  6.415e-03  y = (-2.9285 - (sin(x₅ + x₀) * 0.076332)) - ((x₅ * x₅) - (...
                                      sin((x₁ * -1.9797) - x₀) * -2.2217))
22          1.937e-01  1.785e-02  y = ((-2.9449 - (0.23602 * sin(x₅ * exp(x₂)))) - (x₅ * x₅)...
                                      ) - (sin((x₁ * -1.9801) - x₀) * 2.2144)
23          1.925e-01  5.989e-03  y = ((-2.9449 - (exp(-1.8273) * sin(x₅ * exp(x₂)))) - (x₅ ...
                                      * x₅)) - (sin((x₁ * -1.9801) - x₀) * 2.2144)
24          1.870e-01  2.906e-02  y = ((-2.9835 - (sin(-2.6767 - (exp(x₂) * x₅)) * 0.2271)) ...
                                      - (x₅ * x₅)) - (sin((x₁ * -1.9807) - x₀) * 2.2188)
26          1.869e-01  3.320e-04  y = ((((0.26858 - sin(-2.6311 - (exp(x₂) * x₅))) * 0.21133...
                                      ) + -3.0415) - (x₅ * x₅)) - (sin((x₁ * -1.9806) - x₀) * 2....
                                      2191)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143031_eOBvha/hall_of_fame.csv

In [16]:
show_results(model2_n05)

,complexity,loss,score,equation
3,5,2.471086,3.038596,-2.9474647 - (x5 * x5)
8,12,0.889746,0.946208,(-2.943917 - (x5 * x5)) - sin((x1 * -1.9819144...
9,14,0.203466,0.737718,(-2.9401376 - (x5 * x5)) - (sin((x1 * -1.98069...

best: -x5*x5 - 2.222888*sin(-x0 + x1*(-1.9806954)) - 2.9401376

### Konfiguracja 3 (szum 0.5)

In [17]:
model3_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model3_n05.fit(X_n05, y_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 7.850e+05
Progress: 4602 / 5000 total iterations (92.040%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.092
3           5.528e+01  3.373e-03  y = -10.956 - x₅
4           5.467e+01  1.109e-02  y = -11.093 - sin(x₀)
5           2.471e+00  3.097e+00  y = -2.9476 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = ((x₅ * x₅) * -0.97982) - 3.1117
9           2.389e+00  1.235e-02  y = -2.9541 - (x₅ * (x₅ - (x₄ * 0.035946)))
10          2.360e+00  1.222e-02  y = -3.0128 - ((x₅ * x₅) - sin(x₁ * -2.025))
11          2.318e+00  1.800e-02  y = (-3.006 - (x₅ * x₅)) - sin(sin(x₁ * 2.0184))
12          8.930e-01  9.537e-01  y = (sin(x₁ + (x₁ + x₀)) + -2.9415) - (x₅ * x₅)
13          8.046e-01  1.043e-01  y = exp(sin((x₁ + x₁) + x₀)) + (-4.1843 - (x₅ * x₅))
14          2.124e-01  1.332e+00  y = ((sin((x₁ + x₀) + x₁) * 2.2171) - (x₅ * x₅)) + -2.9344
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.092
3           5.528e+01  3.373e-03  y = -10.956 - x₅
4           5.467e+01  1.109e-02  y = -11.093 - sin(x₀)
5           2.471e+00  3.097e+00  y = -2.9476 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = ((x₅ * x₅) * -0.97982) - 3.1117
9           2.389e+00  1.235e-02  y = -2.9541 - (x₅ * (x₅ - (x₄ * 0.035946)))
10          2.360e+00  1.222e-02  y = -3.0128 - ((x₅ * x₅) - sin(x₁ * -2.025))
11          2.318e+00  1.800e-02  y = (-3.006 - (x₅ * x₅)) - sin(sin(x₁ * 2.0184))
12          8.897e-01  9.574e-01  y = (sin(x₀ + (x₁ * 1.9819)) - (x₅ * x₅)) + -2.9439
13          8.046e-01  1.006e-01  y = exp(sin((x₁ + x₁) + x₀)) + (-4.1843 - (x₅ * x₅))
14          2.124e-01  1.332e+00  y = ((sin((x₁ + x₀) + x₁) * 2.2171) - (x₅ * x₅)) + -2.9344
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143040_PAQruO/hall_of_fame.csv

In [18]:
show_results(model3_n05)

,complexity,loss,score,equation
3,5,2.471086,3.096697,-2.9475615 - (x5 * x5)
10,14,0.212364,1.332022,((sin((x1 + x0) + x1) * 2.2170868) - (x5 * x5)...
8,12,0.889746,0.957383,(sin(x0 + (x1 * 1.9819064)) - (x5 * x5)) + -2....

best: -x5*x5 + sin(x0 + x1 + x1)*2.2170868 - 2.934413

## 4.0 — Zakres [-15, 15], szum $\sigma=2$

In [19]:
np.random.seed(0)
X_w2 = np.random.uniform(-15, 15, (200, 6))
y_w2 = 2.2 * np.sin(X_w2[:, 0] + 2 * X_w2[:, 1]) - X_w2[:, 5]**2 - 3 + np.random.normal(0, 2, 200)

### Konfiguracja 1 (zakres [-15,15], σ=2)

In [20]:
model1_w2 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1_w2.fit(X_w2, y_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 7.490e+05
Progress: 3961 / 5000 total iterations (79.220%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.478
5           9.261e+00  3.074e+00  y = (x₅ * -1.0195) * x₅
7           5.635e+00  2.484e-01  y = ((x₅ * -0.99853) * x₅) + -2.8222
9           5.631e+00  3.749e-04  y = (((x₅ * -0.99872) + 0.0077422) * x₅) + -2.812
11          5.553e+00  6.948e-03  y = (((x₅ * x₅) + sin(exp(x₄))) * -0.9984) + -2.8637
12          5.147e+00  7.585e-02  y = ((sin(x₀ * -1.4498) + (x₅ * x₅)) * -0.9984) + -2.8637
14          5.132e+00  1.488e-03  y = (sin((x₀ * 1.455) + 0.18589) + (x₅ * (x₅ * -0.99853)))...
                                       + -2.8461
15          4.869e+00  5.268e-02  y = (x₅ * (x₅ * -0.99662)) + (-2.9344 + sin((x₀ + exp(x₀))...
                                       * 1.4461))
17          4.812e+00  5.867e-03  y = ((x₅ * (x₅ * -0.99662)) + -2.9344) + sin((exp(x₀) + (x...
                                      ₀ + -0.20566)) * 1.4461)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.478
5           9.261e+00  3.074e+00  y = (x₅ * -1.0195) * x₅
7           5.635e+00  2.484e-01  y = ((x₅ * -0.99853) * x₅) + -2.8222
9           5.631e+00  3.749e-04  y = (((x₅ * -0.99872) + 0.0077422) * x₅) + -2.812
11          5.553e+00  6.948e-03  y = (((x₅ * x₅) + sin(exp(x₄))) * -0.9984) + -2.8637
12          5.147e+00  7.585e-02  y = ((sin(x₀ * -1.4498) + (x₅ * x₅)) * -0.9984) + -2.8637
14          5.132e+00  1.488e-03  y = (sin((x₀ * 1.455) + 0.18589) + (x₅ * (x₅ * -0.99853)))...
                                       + -2.8461
15          4.836e+00  5.953e-02  y = -2.9344 + ((x₅ * (x₅ * -0.99662)) + sin((x₀ + exp(x₀))...
                                       * 1.4461))
17          4.689e+00  1.535e-02  y = (((x₅ * x₅) * -0.99879) + -2.8071) + sin(((cos(x₀) + x...
                                      ₁) + 3.9254) * -2.0135)
18          4.623e+00  1.423e-02  y = ((x₅ * -0.99874) * x₅) + (exp(sin(((cos(x₀) + x₁) + 3....
                                      9705) * -2.007)) + -4.0765)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143046_ppUdL6/hall_of_fame.csv

In [21]:
show_results(model1_w2)

,complexity,loss,score,equation
2,5,9.260938,3.074411,(x5 * -1.0195066) * x5
3,7,5.635046,0.248400,((x5 * -0.99853265) * x5) + -2.822222
6,12,5.147461,0.075854,((sin(x0 * -1.4498069) + (x5 * x5)) * -0.99839...

best: x5*(-0.99853265)*x5 - 2.822222

### Konfiguracja 2 (zakres [-15,15], σ=2)

In [22]:
model2_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model2_w2.fit(X_w2, y_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 4.560e+05
Progress: 2463 / 5000 total iterations (49.260%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.481
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.621e-04  y = (-2.8265 - (x₅ * x₅)) * 0.99853
9           5.554e+00  7.223e-03  y = -2.7191 - ((x₅ * x₅) + sin(exp(x₄)))
10          5.159e+00  7.382e-02  y = (sin(x₀ * 1.4504) - (x₅ * x₅)) + -2.7464
12          4.115e+00  1.131e-01  y = (-2.7253 - (x₅ * x₅)) + sin((x₀ + x₁) + x₁)
14          3.396e+00  9.602e-02  y = ((sin((x₁ + x₀) + x₁) * 2.3008) + -2.7391) - (x₅ * x₅)
16          3.380e+00  2.304e-03  y = ((sin(((x₁ + -0.07202) + x₁) + x₀) * 2.2989) - (x₅ * x...
                                      ₅)) + -2.7295
18          3.380e+00  1.490e-07  y = (sin(x₁ + (x₀ + (x₁ + -0.072002))) * 2.299) + ((-2.035...
                                      2 - (x₅ * x₅)) + -0.69436)
21          3.278e+00  1.019e-02  y = (sin((x₁ + (x₀ * 1.0494)) + x₁) + (-2.736 - (x₅ * x₅))...
                                      ) + sin((x₁ + x₀) + x₁)
23          3.260e+00  2.741e-03  y = ((sin(x₁ + ((x₀ + x₁) * 1.0135)) + -2.7192) - (x₅ * x₅...
                                      )) + sin((x₁ + (x₀ * 1.0388)) + x₁)
25          3.258e+00  4.119e-04  y = ((sin(((x₀ * 1.0369) + (x₁ + -0.063871)) + x₁) + -2.71...
                                      73) - (x₅ * x₅)) + sin(x₁ + ((x₀ + x₁) * 1.0139))
27          3.258e+00  5.960e-08  y = (((sin((x₁ + x₁) + ((x₀ * 1.0369) + -0.063767)) + -3.7...
                                      12) - (x₅ * x₅)) + 0.99472) + sin(((x₀ + x₁) * 1.0139) + x...
                                      ₁)
29          3.251e+00  9.651e-04  y = sin(x₁ + ((sin(((x₃ - -0.78725) + x₀) - sin(x₁)) + x₀)...
                                       + x₁)) + ((sin(x₁ + (x₀ + x₁)) - (x₅ * x₅)) + -2.7398)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.481
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.621e-04  y = (-2.8265 - (x₅ * x₅)) * 0.99853
9           5.547e+00  7.834e-03  y = -2.6367 - (sin(exp(x₄)) + (x₅ * x₅))
10          5.159e+00  7.260e-02  y = (sin(x₀ * 1.4504) - (x₅ * x₅)) + -2.7459
12          4.115e+00  1.131e-01  y = (-2.7253 - (x₅ * x₅)) + sin((x₀ + x₁) + x₁)
13          3.970e+00  3.582e-02  y = (exp(sin(x₁ + (x₀ + x₁))) + -3.9535) - (x₅ * x₅)
14          3.396e+00  1.562e-01  y = (sin(x₁ + (x₁ + x₀)) * 2.3007) + (-2.7393 - (x₅ * x₅))
16          3.215e+00  2.733e-02  y = ((sin((x₀ * 1.0265) + (x₁ + x₁)) * 2.3212) - (x₅ * x₅)...
                                      ) + -2.7137
17          3.196e+00  5.993e-03  y = (sin(sin(((x₀ * 1.0271) + x₁) + x₁)) * 2.6335) + (-2.7...
                                      099 - (x₅ * x₅))
18          3.190e+00  1.947e-03  y = ((sin(sin(sin(x₁ + (x₁ + (x₀ * 1.0276))))) * 2.882) - ...
                                      (x₅ * x₅)) + -2.7073
19          3.178e+00  3.536e-03  y = ((sin(sin(((x₀ * 1.0272) + x₁) + x₁)) * 2.6644) + -2.7...
                                      039) - (x₅ * (x₅ - -0.01562))
20          3.168e+00  3.195e-03  y = ((sin(x₁ + ((x₀ * 1.0262) + x₁)) * (sin(cos(x₂)) + 2.2...
                                      496)) + -2.6917) - (x₅ * x₅)
21          3.006e+00  5.247e-02  y = ((sin(x₁ * -1.1976) + 2.334) * sin((x₁ + x₁) + (x₀ * 1...
                                      .0262))) + (-2.7207 - (x₅ * x₅))
22          2.996e+00  3.485e-03  y = ((sin(sin(x₁ * -1.2009)) + 2.3316) * sin((x₁ + (x₀ * 1...
                                      .0265)) + x₁)) + (-2.7209 - (x₅ * x₅))
23          2.991e+00  1.740e-03  y = ((sin((x₀ * 1.0281) + (x₁ + x₁)) * (sin(x₁ * -1.183) +...
                                       2.3387)) + -2.6543) - (x₅ * (x₅ + 0.019919))
25          2.921e+00  1.168e-02  y = (-2.74 - (x₅ * x₅)) + (sin((x₁ + (x₀ * 1.0272)) + x₁) ...
                                      * (sin(0.54061 - (x₃ * safe_pow(0.96401, x₅))) + 2.2672))
26          2.921e+00  8.065e-05  y = (sin(x₁ + ((x₀ * 1.0266) + x₁)) * (sin((x₁ - exp(x₃ * ...
                                      0.38407)) * -1.126) + 2.3581)) + (-2.7427 - (x₅ * x₅))
27          2.916e+00  1.681e-03  y = (-2.6782 - (x₅ * x₅)) + (sin(((x₁ + (x₀ * 1.0255)) + x...
                                      ₁) * 1.0011) * (sin(0.53906 - (x₃ * safe_pow(0.96399, x₅))...
                                      ) + 2.2709))
29          2.913e+00  6.155e-04  y = ((((sin(0.52686 - (safe_pow(0.96405, x₅) * x₃)) + 1.99...
                                      11) * sin((x₁ + (x₀ * 1.0271)) + x₁)) - -0.070693) * 1.135...
                                      3) + (-2.7512 - (x₅ * x₅))
30          2.891e+00  7.541e-03  y = ((sin((x₁ - exp(x₃ * 0.38181)) * -1.1593) + 2.4263) * ...
                                      sin((x₁ + x₁) + ((x₀ + -0.011926) * 1.031))) + (-2.7963 - ...
                                      (x₅ * (x₅ + 0.035268)))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143052_Kc7Myg/hall_of_fame.csv

In [23]:
show_results(model2_w2)

,complexity,loss,score,equation
2,5,5.644776,3.321948,-2.7146325 - (x5 * x5)
8,14,3.395651,0.156221,(sin(x1 + (x1 + x0)) * 2.3006766) + (-2.739261...
6,12,4.114574,0.113101,(-2.725299 - (x5 * x5)) + sin((x0 + x1) + x1)

best: -x5*x5 + sin(x0 + x1 + x1)*2.3006766 - 2.7392614

### Konfiguracja 3 (zakres [-15,15], σ=2)

In [24]:
model3_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model3_w2.fit(X_w2, y_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.478
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.623e-04  y = (-2.8262 - (x₅ * x₅)) * 0.99853
9           5.548e+00  7.826e-03  y = (-2.6458 - (x₅ * x₅)) - sin(exp(x₄))
10          5.159e+00  7.261e-02  y = (-2.7463 - (x₅ * x₅)) - sin(x₀ * -1.4504)
12          4.108e+00  1.139e-01  y = (-2.7218 - (x₅ * x₅)) - sin((x₁ * -2.0095) - x₀)
14          4.094e+00  1.706e-03  y = (-2.7218 - (x₅ * x₅)) - sin(((x₁ * -2.0095) - x₀) - -0...
                                      .11062)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143102_PAQruO/hall_of_fame.csv

In [25]:
show_results(model3_w2)

,complexity,loss,score,equation
2,5,5.644776,3.321948,-2.7146323 - (x5 * x5)
6,12,4.107902,0.113913,(-2.7218335 - (x5 * x5)) - sin((x1 * -2.009524...
5,10,5.158975,0.072615,(-2.746339 - (x5 * x5)) - sin(x0 * -1.4504223)

best: -x5*x5 - 2.7146323

## 4.0 — Zakres [-15, 15], szum $\sigma=5$

In [26]:
np.random.seed(0)
X_w5 = np.random.uniform(-15, 15, (200, 6))
y_w5 = 2.2 * np.sin(X_w5[:, 0] + 2 * X_w5[:, 1]) - X_w5[:, 5]**2 - 3 + np.random.normal(0, 5, 200)

### Konfiguracja 1 (zakres [-15,15], σ=5)

In [27]:
model1_w5 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1_w5.fit(X_w5, y_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 8.100e+05
Progress: 4388 / 5000 total iterations (87.760%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.633
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.662e+01  2.547e+00  y = (x₅ * -1.0161) * x₅
7           2.375e+01  5.716e-02  y = (x₅ * (x₅ * -0.99738)) + -2.5136
9           2.374e+01  2.401e-04  y = ((x₅ + 0.012771) * (x₅ * -0.99708)) + -2.5309
10          2.335e+01  1.650e-02  y = ((x₅ * x₅) + (sin(x₁) + 2.4112)) * -0.99884
11          2.326e+01  3.815e-03  y = ((exp(sin(x₅)) + (x₅ * x₅)) * -0.99596) + -1.4113
12          2.252e+01  3.207e-02  y = (sin(x₀ * 1.4636) + (x₅ * (x₅ * -0.9973))) + -2.5551
14          2.204e+01  1.088e-02  y = ((x₅ * x₅) * -0.99924) + (-2.4296 + (sin(x₀ * 13.369) ...
                                      * -1.7782))
16          2.183e+01  4.700e-03  y = ((sin(x₀ * 1.4668) * exp(cos(x₅))) + -2.512) + ((x₅ * ...
                                      x₅) * -0.99817)
17          2.178e+01  2.541e-03  y = ((cos(x₅) + 1.69) * sin(x₀ * 1.4676)) + (-2.5277 + ((x...
                                      ₅ * -0.99793) * x₅))
18          2.172e+01  2.677e-03  y = (((x₅ * -0.99843) * x₅) + (sin(x₀ * 1.469) * exp(cos(x...
                                      ₅) + 0.27094))) + -2.5101
19          2.152e+01  9.025e-03  y = ((x₅ * x₅) * -0.99815) + (-2.5283 + (sin(x₀ * 1.4681) ...
                                      * (cos(x₃) + exp(cos(x₅)))))
20          2.140e+01  5.684e-03  y = (x₅ * (x₅ * -0.99748)) + (((exp(cos(x₅)) + cos(exp(x₀)...
                                      )) * sin(x₀ * 1.4636)) + -2.5443)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.633
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.662e+01  2.547e+00  y = (x₅ * -1.0161) * x₅
7           2.375e+01  5.716e-02  y = (x₅ * (x₅ * -0.99738)) + -2.5136
9           2.374e+01  2.401e-04  y = ((x₅ + 0.012771) * (x₅ * -0.99708)) + -2.5309
10          2.335e+01  1.650e-02  y = ((x₅ * x₅) + (sin(x₁) + 2.4112)) * -0.99884
11          2.326e+01  3.815e-03  y = ((exp(sin(x₅)) + (x₅ * x₅)) * -0.99596) + -1.4113
12          2.252e+01  3.207e-02  y = (sin(x₀ * 1.4636) + (x₅ * (x₅ * -0.9973))) + -2.5551
14          2.197e+01  1.235e-02  y = (x₅ * (x₅ * -1.0008)) + ((sin(x₀ * 13.373) * -1.9479) ...
                                      + -2.1004)
15          2.190e+01  3.375e-03  y = ((x₅ * (x₅ * -1.0009)) + (sin(sin(x₀ * 13.375)) * -2.2...
                                      685)) + -2.0908
16          2.183e+01  3.086e-03  y = ((sin(x₀ * 1.4668) * exp(cos(x₅))) + -2.512) + ((x₅ * ...
                                      x₅) * -0.99817)
17          2.178e+01  2.541e-03  y = ((cos(x₅) + 1.69) * sin(x₀ * 1.4676)) + (-2.5277 + ((x...
                                      ₅ * -0.99793) * x₅))
18          2.166e+01  5.347e-03  y = ((exp(cos(x₅ * 0.95216)) * sin(x₀ * 1.4639)) + -2.5012...
                                      ) + (x₅ * (x₅ * -0.99806))
19          2.145e+01  9.693e-03  y = ((x₅ * -0.99854) * x₅) + ((sin(x₀ * 1.447) * (exp(cos(...
                                      x₅)) + cos(x₃))) + -2.4463)
20          2.140e+01  2.347e-03  y = (x₅ * (x₅ * -0.99748)) + (((exp(cos(x₅)) + cos(exp(x₀)...
                                      )) * sin(x₀ * 1.4636)) + -2.5443)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143107_6I5wdN/hall_of_fame.csv

In [28]:
show_results(model1_w5)

,complexity,loss,score,equation
2,5,26.622316,2.547511,(x5 * -1.01606) * x5
3,7,23.746544,0.057156,(x5 * (x5 * -0.9973819)) + -2.513649
7,12,22.523647,0.032067,(sin(x0 * 1.4636205) + (x5 * (x5 * -0.99730337...

best: x5*(-1.01606)*x5

### Konfiguracja 2 (zakres [-15,15], σ=5)

In [29]:
model2_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model2_w5.fit(X_w5, y_w5)

Expressions evaluated per second: 4.120e+05
Progress: 2161 / 5000 total iterations (43.220%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.634
3           4.345e+03  1.610e-02  y = x₂ + -76.085
5           2.378e+01  2.604e+00  y = -2.322 - (x₅ * x₅)
7           2.375e+01  6.469e-04  y = (x₅ * (x₅ * -0.99738)) + -2.5143
8           2.335e+01  1.673e-02  y = (-2.3232 - sin(x₁)) - (x₅ * x₅)
9           2.333e+01  9.209e-04  y = -1.1105 - (exp(sin(x₅)) + (x₅ * x₅))
10          2.285e+01  2.076e-02  y = (sin(x₅ * -6.6832) - (x₅ * x₅)) - 2.3896
12          2.265e+01  4.425e-03  y = (-2.2846 - (x₅ * x₅)) + cos((x₁ - x₅) - -0.80223)
13          2.243e+01  9.667e-03  y = (sin(-0.62138 - (x₁ - cos(x₅))) + -2.3172) - (x₅ * x₅)
15          2.237e+01  1.303e-03  y = ((cos(x₅ * 2.8897) - (x₅ * x₅)) + -2.242) + cos(x₁ + 2...
                                      .2127)
16          2.217e+01  9.304e-03  y = cos(x₅ * 2.8838) + (-2.3268 - ((sin(x₁) + sin(x₅)) + (...
                                      x₅ * x₅)))
17          2.203e+01  6.244e-03  y = (cos(x₅ * 2.8823) + -2.2325) - ((x₅ * x₅) + sin(x₁ + (...
                                      -0.70772 - x₅)))
18          2.200e+01  1.105e-03  y = (cos(x₅ * 2.8823) + -2.2325) - ((x₅ * x₅) + sin((x₁ + ...
                                      sin(x₅)) - x₅))
20          2.173e+01  6.218e-03  y = ((cos(x₅ * 2.8893) - (x₅ * x₅)) + -2.2616) + sin((x₁ +...
                                       sin(-1.5391 - x₅)) + -2.4825)
22          2.172e+01  2.289e-04  y = ((-2.2616 + cos(x₅ * 2.8893)) - (x₅ * x₅)) + sin((x₁ +...
                                       sin((x₀ * 0.24839) - x₅)) + -2.4825)
23          2.147e+01  1.162e-02  y = ((sin((x₅ * 0.13658) * x₅) * -1.5807) - (x₅ * x₅)) + (...
                                      sin((x₃ * 0.38778) * (x₅ * x₅)) + -1.9962)
25          2.147e+01  3.785e-06  y = (((-1.5807 * sin(x₅ * (0.13658 * x₅))) - (x₅ * x₅)) + ...
                                      (-1.9962 + sin((0.38778 * x₃) * (x₅ * x₅)))) - 0.023819
27          2.109e+01  8.981e-03  y = (sin((x₅ * ((x₄ - x₅) * safe_pow(0.70336, x₅))) * x₅) ...
                                      - (x₅ * x₅)) + (-2.0203 + sin(0.38748 * (x₃ * (x₅ * x₅))))
29          2.100e+01  2.133e-03  y = ((sin((x₅ * ((x₄ - x₅) * safe_pow(0.70336, x₅))) * x₅)...
                                       - (x₅ * x₅)) + (-2.0203 + sin(((x₃ * 0.38748) * x₅) * x₅)...
                                      )) + -0.29769
30          2.083e+01  8.311e-03  y = (-2.0203 + (sin(((safe_pow(0.70336, x₅) * (x₄ - x₅)) *...
                                       x₅) * x₅) - (x₅ * x₅))) + (sin(((x₅ * x₅) * x₃) * 0.38748...
                                      ) - sin(x₅))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 4.370e+05
Progress: 4800 / 5000 total iterations (96.000%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.634
3           4.345e+03  1.610e-02  y = x₂ + -76.085
5           2.378e+01  2.604e+00  y = -2.322 - (x₅ * x₅)
7           2.375e+01  6.469e-04  y = (x₅ * (x₅ * -0.99738)) + -2.5143
8           2.335e+01  1.673e-02  y = (-2.3232 - sin(x₁)) - (x₅ * x₅)
9           2.333e+01  9.209e-04  y = -1.1105 - (exp(sin(x₅)) + (x₅ * x₅))
10          2.256e+01  3.378e-02  y = (sin(x₀ * 1.4644) - (x₅ * x₅)) + -2.3567
12          2.212e+01  9.792e-03  y = (-2.3323 - (x₅ * x₅)) + sin((x₁ + x₀) + x₁)
14          2.206e+01  1.329e-03  y = (sin((x₁ + (x₁ + -0.22142)) + x₀) + -2.3195) - (x₅ * x...
                                      ₅)
15          2.173e+01  1.491e-02  y = (-2.3339 - (sin(x₁) + (x₅ * x₅))) + sin((x₀ + x₁) + x₁...
                                      )
16          2.172e+01  5.365e-04  y = sin((x₀ + x₁) + x₁) + (-2.3333 - (sin(sin(x₁)) + (x₅ *...
                                       x₅)))
17          2.138e+01  1.596e-02  y = sin((x₁ + x₀) + x₁) + (-2.3359 - ((x₅ * x₅) + sin(x₁ -...
                                       x₅)))
18          2.111e+01  1.243e-02  y = sin(x₁ + (x₀ + x₁)) + (-2.3666 - ((x₅ * x₅) + sin(x₁ -...
                                       cos(x₅))))
19          2.074e+01  1.774e-02  y = sin(x₁ + (x₀ + x₁)) + ((-2.3522 - (x₅ * x₅)) + cos(x₅ ...
                                      * (x₁ + -8.747)))
21          2.063e+01  2.654e-03  y = sin((x₀ + x₁) + x₁) + ((cos((cos(exp(x₀)) - x₅) + x₁) ...
                                      + -2.2651) - (x₅ * x₅))
22          2.035e+01  1.354e-02  y = sin((x₁ + x₀) + x₁) + (cos(1.237 + (x₁ - (x₅ + exp(x₀)...
                                      ))) + (-2.3301 - (x₅ * x₅)))
24          2.006e+01  7.184e-03  y = sin(x₁ + -8.7918) + (cos((x₁ + -8.7491) * x₅) + ((-2.3...
                                      274 - (x₅ * x₅)) + sin((x₁ + x₀) + x₁)))
26          1.996e+01  2.514e-03  y = (((-2.3628 - (x₅ * x₅)) + cos(x₅ * (x₁ + -8.7473))) + ...
                                      sin((x₀ + x₁) + x₁)) + sin(x₁ + (x₀ + x₁))
28          1.988e+01  2.015e-03  y = ((sin(x₁ + (x₀ + x₁)) + (sin(((x₀ + x₁) - 0.3254) + x₁...
                                      ) - (x₅ * x₅))) + -2.344) + cos(x₅ * (x₁ + -8.7477))
29          1.949e+01  2.019e-02  y = cos(x₁ + ((1.2106 - x₅) - exp(x₀))) + (cos(x₁ * (x₅ - ...
                                      0.29078)) + ((-2.3427 - (x₅ * x₅)) + sin(x₁ + (x₁ + x₀))))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.634
3           4.345e+03  1.610e-02  y = x₂ + -76.085
5           2.378e+01  2.604e+00  y = -2.322 - (x₅ * x₅)
7           2.375e+01  6.469e-04  y = (x₅ * (x₅ * -0.99738)) + -2.5143
8           2.335e+01  1.673e-02  y = (-2.3232 - sin(x₁)) - (x₅ * x₅)
9           2.333e+01  9.209e-04  y = -1.1105 - (exp(sin(x₅)) + (x₅ * x₅))
10          2.256e+01  3.378e-02  y = (sin(x₀ * 1.4644) - (x₅ * x₅)) + -2.3567
12          2.212e+01  9.792e-03  y = (-2.3323 - (x₅ * x₅)) + sin((x₁ + x₀) + x₁)
14          2.190e+01  5.076e-03  y = sin(((x₀ + x₁) + x₁) * 1.0324) + (-2.2979 - (x₅ * x₅))
15          2.173e+01  7.414e-03  y = (-2.3339 - (sin(x₁) + (x₅ * x₅))) + sin((x₀ + x₁) + x₁...
                                      )
16          2.172e+01  5.365e-04  y = sin((x₀ + x₁) + x₁) + (-2.3333 - (sin(sin(x₁)) + (x₅ *...
                                       x₅)))
17          2.138e+01  1.596e-02  y = sin((x₁ + x₀) + x₁) + (-2.3359 - ((x₅ * x₅) + sin(x₁ -...
                                       x₅)))
18          2.111e+01  1.243e-02  y = sin(x₁ + (x₀ + x₁)) + (-2.3666 - ((x₅ * x₅) + sin(x₁ -...
                                       cos(x₅))))
19          2.074e+01  1.774e-02  y = sin(x₁ + (x₀ + x₁)) + ((-2.3522 - (x₅ * x₅)) + cos(x₅ ...
                                      * (x₁ + -8.747)))
21          2.063e+01  2.654e-03  y = sin((x₀ + x₁) + x₁) + ((cos((cos(exp(x₀)) - x₅) + x₁) ...
                                      + -2.2651) - (x₅ * x₅))
22          2.035e+01  1.387e-02  y = (cos(x₁ + ((1.2103 - x₅) - exp(x₀))) + (-2.2873 - (x₅ ...
                                      * x₅))) + sin(x₁ + (x₁ + x₀))
24          2.006e+01  7.022e-03  y = sin(x₁ + -8.7918) + (cos((x₁ + -8.7491) * x₅) + ((-2.3...
                                      274 - (x₅ * x₅)) + sin((x₁ + x₀) + x₁)))
26          1.996e+01  2.514e-03  y = (((-2.3628 - (x₅ * x₅)) + cos(x₅ * (x₁ + -8.7473))) + ...
                                      sin((x₀ + x₁) + x₁)) + sin(x₁ + (x₀ + x₁))
27          1.986e+01  5.364e-03  y = cos(x₁ * -0.69324) + (((-2.0872 - (x₅ * x₅)) + cos(((x...
                                      ₁ + 1.0915) - x₅) - exp(x₀))) + sin(x₁ + (x₁ + x₀)))
29          1.949e+01  9.431e-03  y = sin((x₁ + x₁) + x₀) + ((cos(((1.2103 - x₅) - exp(x₀)) ...
                                      + x₁) + (-2.3427 - (x₅ * x₅))) + cos(x₁ * (0.29073 - x₅)))
───────────────────────────────────────────────────────────────────────────────────────────────────

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143113_SBn4Bs/hall_of_fame.csv

In [30]:
show_results(model2_w5)

,complexity,loss,score,equation
2,5,23.777332,2.604020,-2.3219779 - (x5 * x5)
6,10,22.556126,0.033780,(sin(x0 * 1.4643761) - (x5 * x5)) + -2.3566928
13,19,20.742260,0.017744,sin(x1 + (x0 + x1)) + ((-2.3522458 - (x5 * x5)...

best: -x5*x5 - 2.3219779

### Konfiguracja 3 (zakres [-15,15], σ=5)

In [31]:
model3_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings=safe_pow_sympy,
    **default_pysr_params,
)
model3_w5.fit(X_w5, y_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

Expressions evaluated per second: 7.660e+05
Progress: 4553 / 5000 total iterations (91.060%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.634
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.378e+01  2.604e+00  y = -2.3215 - (x₅ * x₅)
7           2.375e+01  6.469e-04  y = (x₅ * (x₅ * -0.99738)) - 2.5135
8           2.335e+01  1.673e-02  y = (-2.3233 - (x₅ * x₅)) - sin(x₁)
9           2.333e+01  9.209e-04  y = -1.1102 - (exp(sin(x₅)) + (x₅ * x₅))
10          2.256e+01  3.378e-02  y = -2.3568 - (sin(x₀ * -1.4643) + (x₅ * x₅))
12          2.204e+01  1.157e-02  y = -2.3429 - ((x₅ * x₅) - sin(x₀ - (x₁ * -2.0302)))
14          2.194e+01  2.204e-03  y = -2.3287 - ((x₅ * x₅) - sin((x₀ - (x₁ * -2.0391)) + -0....
                                      28811))
15          2.166e+01  1.279e-02  y = -2.3437 - ((x₅ * x₅) + (sin(x₁) - sin(x₀ - (x₁ * -2.02...
                                      86))))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.634
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.378e+01  2.604e+00  y = -2.3215 - (x₅ * x₅)
7           2.375e+01  6.469e-04  y = (x₅ * (x₅ * -0.99738)) - 2.5135
8           2.335e+01  1.673e-02  y = (-2.3233 - (x₅ * x₅)) - sin(x₁)
9           2.333e+01  9.209e-04  y = -1.1102 - (exp(sin(x₅)) + (x₅ * x₅))
10          2.256e+01  3.378e-02  y = -2.3568 - (sin(x₀ * -1.4643) + (x₅ * x₅))
12          2.204e+01  1.157e-02  y = (-2.3424 - (x₅ * x₅)) + sin(x₀ - (x₁ * -2.0302))
14          2.194e+01  2.204e-03  y = -2.3287 - ((x₅ * x₅) - sin((x₀ - (x₁ * -2.0391)) + -0....
                                      28811))
15          2.166e+01  1.279e-02  y = -2.3437 - ((x₅ * x₅) + (sin(x₁) - sin(x₀ - (x₁ * -2.02...
                                      86))))
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'safe_pow': <function <la...t 0x3173608b0>}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143124_PAQruO/hall_of_fame.csv

In [32]:
show_results(model3_w5)

,complexity,loss,score,equation
2,5,23.777332,2.604020,-2.321463 - (x5 * x5)
6,10,22.556124,0.033780,-2.3567507 - (sin(x0 * -1.4643459) + (x5 * x5))
4,8,23.352629,0.016728,(-2.3232915 - (x5 * x5)) - sin(x1)

best: -x5*x5 - 2.321463

## 5.0 — Operator liczb pierwszych $p(i)$

Funkcja: $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$

### Instalacja Primes.jl i definicja operatora `p`

In [33]:
from pysr import jl

jl.seval("""
import Pkg
Pkg.add(\"Primes\")
""")

   Resolving package versions...
     Project No packages added to or removed from `/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/julia_env/Project.toml`
    Manifest No packages added to or removed from `/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/julia_env/Manifest.toml`

In [34]:
jl.seval("using Primes: prime")

In [35]:
jl.seval("""
function p(i::T) where T
    if 0.5 < i < 1000
        return T(prime(round(Int, i)))
    else
        return T(NaN)
    end
end
""")

p (generic function with 1 method)

Definicja `sympy_p` oraz pomocnicza funkcja Pythonowa do generowania próbek.

In [36]:
class sympy_p(sympy.Function):
    pass

def p_python(x0_val):
    i = int(np.floor(x0_val))
    if 1 <= i <= 999:
        return float(sympy.prime(i))
    return np.nan

In [37]:
def make_data_prime(low, high, n=200, noise_std=0.0, seed=0):
    rng = np.random.default_rng(seed)
    # generujemy więcej próbek, bo część x0 daje NaN
    X_raw = rng.uniform(low, high, (n * 6, 6))
    p_vals = np.array([p_python(x) for x in X_raw[:, 0]])
    y_raw = 2.2 * np.sin(X_raw[:, 0] + 2 * X_raw[:, 1]) - X_raw[:, 5]**2 - p_vals
    if noise_std > 0:
        y_raw += rng.normal(0, noise_std, len(y_raw))
    mask = ~np.isnan(y_raw)
    return X_raw[mask][:n], y_raw[mask][:n]

### 5.0 — Bez szumu, zakres [-5, 5]

In [38]:
X_p, y_p = make_data_prime(-5, 5)
print(f'Próbek: {len(y_p)}')

Próbek: 200

### Konfiguracja 1 z operatorem `p` (bez szumu)

In [39]:
model1_p = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p.fit(X_p, y_p)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 5.890e+05
Progress: 3458 / 5000 total iterations (69.160%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.861
4           5.058e+01  2.706e-02  y = cos(x₅) + -11.678
5           1.433e+01  1.261e+00  y = x₅ * (x₅ * -1.2969)
7           3.456e+00  7.112e-01  y = (x₀ + (x₅ * x₅)) * -1.0779
9           2.617e+00  1.391e-01  y = (x₀ * -1.4628) + (x₅ * (x₅ * -0.9778))
10          2.531e+00  3.363e-02  y = ((x₅ * x₅) + p(x₀ * 0.8964)) * -0.97731
12          2.380e+00  3.062e-02  y = (p((x₀ * 0.98267) + -0.4172) + (x₅ * x₅)) * -0.98774
15          2.189e+00  2.787e-02  y = (cos(cos(x₁ + 1.041)) * (x₀ * -1.8986)) + (x₅ * (x₅ * ...
                                      -0.98279))
16          9.839e-01  7.998e-01  y = sin(x₁ + (x₀ + x₁)) + ((x₀ * -1.4563) + (x₅ * (x₅ * -0...
                                      .98621)))
18          3.320e-01  5.432e-01  y = (sin((x₁ + x₁) + x₀) * 2.1464) + ((x₀ * -1.4489) + (x₅...
                                       * (x₅ * -0.99584)))
20          3.015e-01  4.831e-02  y = ((((x₀ * -0.73245) + (x₅ * (x₅ * -0.46458))) + sin((x₁...
                                       + x₀) + x₁)) + 0.24392) * 2.1609
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.861
4           5.058e+01  2.706e-02  y = cos(x₅) + -11.678
5           1.433e+01  1.261e+00  y = x₅ * (x₅ * -1.2969)
7           3.456e+00  7.112e-01  y = (x₀ + (x₅ * x₅)) * -1.0779
9           2.617e+00  1.391e-01  y = (x₀ * -1.4628) + (x₅ * (x₅ * -0.9778))
10          2.404e+00  8.477e-02  y = ((x₅ * x₅) + p(x₀ + -0.4975)) * -0.98934
12          2.374e+00  6.408e-03  y = (p((x₀ + -0.40094) * 0.97767) + (x₅ * x₅)) * -0.98786
14          2.341e+00  6.990e-03  y = sin(x₁ * -1.9919) + ((x₅ * (x₅ * -0.97543)) + (x₀ * -1...
                                      .481))
15          2.189e+00  6.690e-02  y = (cos(cos(x₁ + 1.041)) * (x₀ * -1.8986)) + (x₅ * (x₅ * ...
                                      -0.98279))
16          9.839e-01  7.998e-01  y = sin(x₁ + (x₀ + x₁)) + ((x₀ * -1.4563) + (x₅ * (x₅ * -0...
                                      .98621)))
18          3.320e-01  5.432e-01  y = ((x₀ * -1.4489) + (x₅ * (x₅ * -0.99584))) + (2.1465 * ...
                                      sin(x₁ + (x₁ + x₀)))
20          3.015e-01  4.831e-02  y = ((((x₀ * -0.73245) + (x₅ * (x₅ * -0.46458))) + sin((x₁...
                                       + x₀) + x₁)) + 0.24392) * 2.1609
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143140_2GQyRW/hall_of_fame.csv

In [40]:
show_results(model1_p)

,complexity,loss,score,equation
2,5,14.333841,1.260923,x5 * (x5 * -1.296927)
9,16,0.983938,0.799834,sin(x1 + (x0 + x1)) + ((x0 * -1.456332) + (x5 ...
3,7,3.456479,0.711186,(x0 + (x5 * x5)) * -1.0778502

best: x0*(-1.4489) + x5*x5*(-0.9958418) + 2.1464548*sin(x0 + x1 + x1)

### Konfiguracja 2 z operatorem `p` (bez szumu)

In [41]:
model2_p = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model2_p.fit(X_p, y_p)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Expressions evaluated per second: 4.080e+05
Progress: 2302 / 5000 total iterations (46.040%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8115 - x₀
4           5.058e+01  1.828e-02  y = cos(x₅) + -11.678
5           5.660e+00  2.190e+00  y = -4.263 - (x₅ * x₅)
7           2.985e+00  3.198e-01  y = (-1.2136 - (x₅ * x₅)) - x₀
9           2.581e+00  7.271e-02  y = -0.25762 - ((x₅ * x₅) + safe_pow(x₀, 1.2265))
10          2.545e+00  1.412e-02  y = ((-1.2334 - (x₅ * x₅)) + sin(x₀)) - x₀
11          2.525e+00  7.804e-03  y = x₀ + (-1.7343 - (safe_pow(x₀, 1.5038) + (x₅ * x₅)))
12          2.474e+00  2.062e-02  y = ((sin(x₀ + -0.49333) - x₀) - (x₅ * x₅)) + -1.4527
13          2.451e+00  9.229e-03  y = (-1.4078 + sin(x₀ - sin(x₁))) - ((x₅ * x₅) + x₀)
14          9.506e-01  9.472e-01  y = sin(x₁ + (x₀ + x₁)) - (safe_pow(x₀, 1.2677) + (x₅ * x₅...
                                      ))
16          2.868e-01  5.992e-01  y = (sin((x₁ + x₁) + x₀) * 2.1523) - (safe_pow(x₀, 1.2748)...
                                       + (x₅ * x₅))
18          2.674e-01  3.505e-02  y = ((sin(x₁ + (x₁ + x₀)) + -0.11338) * 2.1514) - (safe_po...
                                      w(x₀, 1.2426) + (x₅ * x₅))
20          2.399e-01  5.415e-02  y = (sin(x₁ + (x₀ + x₁)) * 2.1409) - ((x₅ * x₅) + (safe_po...
                                      w(x₀ + -0.98509, 1.3242) - -1.5214))
23          2.329e-01  9.926e-03  y = (2.1337 * sin(x₁ + (x₀ + x₁))) - (safe_pow(x₀, 1.3706)...
                                       + (((log(x₀) * -1.2019) + (x₅ * x₅)) - -0.78545))
25          2.322e-01  1.384e-03  y = (sin((x₁ - -0.016882) + (x₁ + x₀)) * 2.1363) - ((((log...
                                      (x₀) * -1.206) + (x₅ * x₅)) - -0.78426) + safe_pow(x₀, 1.3...
                                      712))
26          2.081e-01  1.099e-01  y = ((sin(x₁ + (x₀ + x₁)) - (x₀ + ((x₅ * x₅) + 1.4546))) +...
                                       sin(x₀ + -0.35189)) + sin(x₁ + (x₀ + x₁))
28          2.071e-01  2.242e-03  y = (sin(x₁ + (x₀ + x₁)) + ((sin((x₁ + x₀) + x₁) - ((x₅ * ...
                                      (x₅ + -0.011069)) + x₀)) + -1.4539)) + sin(x₀ + -0.35122)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 4.060e+05
Progress: 4599 / 5000 total iterations (91.980%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8115 - x₀
4           5.058e+01  1.828e-02  y = cos(x₅) + -11.678
5           5.660e+00  2.190e+00  y = -4.263 - (x₅ * x₅)
7           2.985e+00  3.199e-01  y = (x₀ * -1.2344) - (x₅ * x₅)
9           2.560e+00  7.684e-02  y = -0.36974 - ((x₅ * x₅) + safe_pow(1.5083, x₀))
10          2.492e+00  2.689e-02  y = (sin(x₀) * 2.3591) - ((x₅ * x₅) + 4.3096)
12          2.471e+00  4.218e-03  y = ((sin(x₀) * 2.4181) - ((x₅ * x₅) + 4.5588)) * 0.97951
13          2.408e+00  2.593e-02  y = sin(exp(x₀ + 0.51629)) - ((x₅ * x₅) + safe_pow(x₀, 1.2...
                                      516))
14          9.506e-01  9.294e-01  y = sin(x₁ + (x₀ + x₁)) - (safe_pow(x₀, 1.2677) + (x₅ * x₅...
                                      ))
16          2.868e-01  5.992e-01  y = (sin((x₁ + x₁) + x₀) * 2.1523) - (safe_pow(x₀, 1.2748)...
                                       + (x₅ * x₅))
18          2.674e-01  3.505e-02  y = (sin((x₁ + x₀) + x₁) * 2.1514) - (((x₅ * x₅) + safe_po...
                                      w(x₀, 1.2426)) - -0.24402)
19          2.301e-01  1.500e-01  y = (sin(x₁ + (x₁ + x₀)) * 2.1505) - (((x₅ * x₅) + (1.2991...
                                       - sin(x₀))) + x₀)
20          2.240e-01  2.691e-02  y = (sin((x₀ + x₁) + x₁) * 2.1329) - (safe_pow(x₀, 1.2725)...
                                       + (safe_pow(x₀, -3.5952) + (x₅ * x₅)))
21          1.989e-01  1.190e-01  y = (sin((x₁ + x₀) + x₁) * 2.1356) - ((x₅ * x₅) + ((x₀ + s...
                                      in(0.34166 - x₀)) + 1.4543))
23          1.979e-01  2.614e-03  y = (sin((x₀ + x₁) + x₁) * 2.1364) - (sin(0.34075 - x₀) + ...
                                      (x₀ + ((x₅ * (x₅ + -0.011688)) + 1.4535)))
25          1.955e-01  5.909e-03  y = ((sin(x₀ - 0.3435) + ((sin((x₁ + x₀) + x₁) * 2.1403) -...
                                       (x₀ + (x₅ * x₅)))) - 1.4522) - (x₂ * 0.019977)
27          1.955e-01  8.941e-08  y = ((sin((1.3381 - x₀) + 2.1469) - 1.4521) - (x₂ * 0.0199...
                                      89)) + ((sin(x₁ + (x₀ + x₁)) * 2.1403) - (x₀ + (x₅ * x₅)))
28          1.949e-01  3.342e-03  y = ((sin(3.4849 - x₀) - 1.4521) - ((x₂ + sin(x₃)) * 0.019...
                                      989)) + ((sin((x₁ + x₀) + x₁) * 2.1403) - (x₀ + (x₅ * x₅))...
                                      )
30          1.949e-01  6.620e-05  y = (((sin((1.3378 - x₀) + 2.1466) - 1.4528) - ((x₂ + sin(...
                                      x₃)) * 0.021669)) + (sin((x₁ + x₀) + x₁) * 2.1403)) - (x₀ ...
                                      + (x₅ * x₅))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8115 - x₀
4           5.058e+01  1.828e-02  y = cos(x₅) + -11.678
5           5.660e+00  2.190e+00  y = -4.263 - (x₅ * x₅)
7           2.985e+00  3.199e-01  y = (x₀ * -1.2344) - (x₅ * x₅)
9           2.560e+00  7.684e-02  y = -0.36974 - ((x₅ * x₅) + safe_pow(1.5083, x₀))
10          2.492e+00  2.689e-02  y = (sin(x₀) * 2.3591) - ((x₅ * x₅) + 4.3096)
12          2.303e+00  3.942e-02  y = sin(x₁ * -2.0041) - (safe_pow(x₀, 1.2695) + (x₅ * x₅))
13          2.295e+00  3.377e-03  y = sin(sin(x₁ * -1.9931)) - (safe_pow(x₀, 1.2688) + (x₅ *...
                                       x₅))
14          9.506e-01  8.815e-01  y = sin(x₁ + (x₀ + x₁)) - (safe_pow(x₀, 1.2677) + (x₅ * x₅...
                                      ))
16          2.868e-01  5.992e-01  y = (sin((x₁ + x₁) + x₀) * 2.1523) - (safe_pow(x₀, 1.2748)...
                                       + (x₅ * x₅))
18          2.674e-01  3.505e-02  y = (sin((x₁ + x₀) + x₁) * 2.1514) - (((x₅ * x₅) + safe_po...
                                      w(x₀, 1.2426)) - -0.24402)
19          2.301e-01  1.500e-01  y = (sin(x₁ + (x₁ + x₀)) * 2.1505) - ((((x₅ * x₅) + 1.2991...
                                      ) - sin(x₀)) + x₀)
20          2.240e-01  2.691e-02  y = (sin((x₀ + x₁) + x₁) * 2.1329) - (safe_pow(x₀, 1.2725)...
                                       + (safe_pow(x₀, -3.5952) + (x₅ * x₅)))
21          1.989e-01  1.190e-01  y = (((sin(x₁ + (x₀ + x₁)) * 2.1356) - ((x₅ * x₅) + x₀)) +...
                                       sin(-2.7999 - x₀)) - 1.4543
23          1.979e-01  2.614e-03  y = (sin((x₀ + x₁) + x₁) * 2.1364) - (sin(0.34075 - x₀) + ...
                                      (x₀ + ((x₅ * (x₅ + -0.011688)) + 1.4535)))
25          1.955e-01  5.909e-03  y = sin(x₀ - 0.3435) + ((((sin((x₁ + x₁) + x₀) * 2.1403) -...
                                       (x₀ + (x₅ * x₅))) - 1.4522) - (x₂ * 0.019977))
28          1.949e-01  1.158e-03  y = ((((sin(x₁ + (x₀ + x₁)) * 2.1403) - (x₀ + (x₅ * x₅))) ...
                                      + sin(-2.7988 - x₀)) - 1.4528) - ((x₂ + sin(x₃)) * 0.02166...
                                      9)
29          1.930e-01  9.715e-03  y = ((((sin((x₁ + x₀) + x₁) * 2.1403) - (x₀ + (x₅ * x₅))) ...
                                      + sin(-2.7988 - x₀)) - 1.4528) - ((x₂ + sin(exp(x₀))) * 0....
                                      021669)
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143148_WgPEBO/hall_of_fame.csv

In [42]:
show_results(model2_p)

,complexity,loss,score,equation
3,5,5.659594,2.190194,-4.26304 - (x5 * x5)
9,14,0.950600,0.881503,"sin(x1 + (x0 + x1)) - (safe_pow(x0, 1.2676626)..."
10,16,0.286771,0.599204,(sin((x1 + x1) + x0) * 2.1523123) - (safe_pow(...

best: -(x0**1.2748233 + x5*x5) + sin(x0 + x1 + x1)*2.1523123

### Konfiguracja 3 z operatorem `p` (bez szumu)

In [43]:
model3_p = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model3_p.fit(X_p, y_p)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

Expressions evaluated per second: 6.080e+05
Progress: 3738 / 5000 total iterations (74.760%)
════════════════════════════════════════════════════════════════════════════════════════════════════

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8112 - x₀
5           5.660e+00  1.104e+00  y = -4.263 - (x₅ * x₅)
7           2.645e+00  3.804e-01  y = (x₀ * -1.4136) - (x₅ * x₅)
9           2.581e+00  1.211e-02  y = -0.25759 - ((x₅ * x₅) + safe_pow(x₀, 1.2265))
10          2.402e+00  7.210e-02  y = (x₅ * (x₅ * -0.98467)) - p(x₀ + -0.49424)
12          2.375e+00  5.639e-03  y = ((x₀ * -1.4262) - sin(x₁ + x₁)) - (x₅ * x₅)
13          2.364e+00  4.747e-03  y = ((x₀ * -1.4248) - sin(sin(x₁ + x₁))) - (x₅ * x₅)
14          2.336e+00  1.186e-02  y = (((x₀ * -1.5244) - sin(x₁ + x₁)) - (x₅ * x₅)) * 0.9736...
                                      7
15          1.304e+00  5.828e-01  y = ((x₀ * -1.4258) - sin((x₁ + x₁) - sin(x₀))) - (x₅ * x₅...
                                      )
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8112 - x₀
5           5.660e+00  1.104e+00  y = -4.263 - (x₅ * x₅)
7           2.645e+00  3.804e-01  y = (x₀ * -1.4136) - (x₅ * x₅)
9           2.581e+00  1.211e-02  y = -0.25759 - ((x₅ * x₅) + safe_pow(x₀, 1.2265))
10          2.402e+00  7.221e-02  y = ((x₅ * x₅) * -0.99093) - p(x₀ + -0.49055)
12          2.375e+00  5.582e-03  y = ((x₀ * -1.4262) - sin(x₁ + x₁)) - (x₅ * x₅)
13          2.364e+00  4.747e-03  y = ((x₀ * -1.4248) - sin(sin(x₁ + x₁))) - (x₅ * x₅)
14          9.945e-01  8.657e-01  y = (x₀ * -1.4258) + (sin(x₁ + (x₀ + x₁)) - (x₅ * x₅))
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143200_sXUFFP/hall_of_fame.csv

In [44]:
show_results(model3_p)

,complexity,loss,score,equation
2,5,5.659594,1.104241,-4.2630405 - (x5 * x5)
8,14,0.994522,0.865675,(x0 * -1.4257586) + (sin(x1 + (x0 + x1)) - (x5...
3,7,2.644633,0.380410,(x0 * -1.4136101) - (x5 * x5)

best: x0*(-1.4257586) - x5*x5 + sin(x0 + x1 + x1)

### 5.0 — Szum $\sigma=0.5$, zakres [-5, 5]

In [45]:
X_p_n05, y_p_n05 = make_data_prime(-5, 5, noise_std=0.5)

### Konfiguracja 1 z operatorem `p` (szum 0.5)

In [46]:
model1_p_n05 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p_n05.fit(X_p_n05, y_p_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 5.170e+05
Progress: 3050 / 5000 total iterations (61.000%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.902
4           5.090e+01  2.654e-02  y = cos(x₅) + -11.72
5           1.463e+01  1.247e+00  y = x₅ * (x₅ * -1.3003)
7           3.753e+00  6.801e-01  y = ((x₅ * x₅) + x₀) * -1.0674
9           2.893e+00  1.302e-01  y = (x₀ * -1.4638) + (x₅ * (x₅ * -0.98098))
11          2.891e+00  3.510e-04  y = ((x₅ * (x₅ * -0.98301)) + (x₀ * -1.4983)) + 0.13535
12          2.776e+00  4.037e-02  y = (((x₅ * x₅) * -0.98087) + (sin(x₀) * 2.3133)) + -4.495...
                                      2
14          2.612e+00  3.060e-02  y = (((x₅ * x₅) + sin(x₁ + x₁)) * -0.97807) + (x₀ * -1.481...
                                      3)
15          2.600e+00  4.431e-03  y = (((x₅ * x₅) + sin(sin(x₁ + x₁))) * -0.97807) + (x₀ * -...
                                      1.4813)
16          1.238e+00  7.423e-01  y = (x₅ * (x₅ * -0.98938)) + ((x₀ * -1.4578) + sin(x₀ + (x...
                                      ₁ * 1.9793)))
18          5.654e-01  3.918e-01  y = ((x₀ * -1.4503) + ((x₅ * -0.99917) * x₅)) + (sin(x₀ + ...
                                      (x₁ * 1.9893)) * 2.1633)
20          5.486e-01  1.510e-02  y = (x₅ * (x₅ * -1.0052)) + (0.394 + ((sin(x₀ + (x₁ * 1.99...
                                      35)) + (x₀ * -0.71286)) * 2.1746))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.902
4           5.090e+01  2.654e-02  y = cos(x₅) + -11.72
5           1.463e+01  1.247e+00  y = x₅ * (x₅ * -1.3003)
7           3.725e+00  6.839e-01  y = ((x₅ * x₅) + x₀) * -1.0806
9           2.893e+00  1.264e-01  y = (x₀ * -1.4638) + (x₅ * (x₅ * -0.98098))
11          2.891e+00  3.510e-04  y = ((x₅ * (x₅ * -0.98301)) + (x₀ * -1.4983)) + 0.13535
12          2.776e+00  4.037e-02  y = (((x₅ * x₅) * -0.98087) + (sin(x₀) * 2.3133)) + -4.495...
                                      2
14          2.612e+00  3.062e-02  y = (x₀ * -1.4854) + ((sin(x₁ + x₁) + (x₅ * x₅)) * -0.9768...
                                      1)
15          2.600e+00  4.389e-03  y = (((x₅ * x₅) + sin(sin(x₁ + x₁))) * -0.97807) + (x₀ * -...
                                      1.4813)
16          1.238e+00  7.423e-01  y = (x₅ * (x₅ * -0.98938)) + ((x₀ * -1.4578) + sin(x₀ + (x...
                                      ₁ * 1.9793)))
18          5.654e-01  3.918e-01  y = (((x₅ * -0.99917) * x₅) + (sin((x₁ * 1.9893) + x₀) * 2...
                                      .1633)) + (x₀ * -1.4503)
20          5.486e-01  1.510e-02  y = (x₅ * (x₅ * -1.0052)) + ((((x₀ * -0.71277) + sin(x₀ + ...
                                      (x₁ * 1.9935))) * 2.1748) + 0.3939)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143207_jKrjqi/hall_of_fame.csv

In [47]:
show_results(model1_p_n05)

,complexity,loss,score,equation
2,5,14.626331,1.247088,x5 * (x5 * -1.300273)
9,16,1.237752,0.742257,(x5 * (x5 * -0.9893826)) + ((x0 * -1.4578174) ...
3,7,3.724829,0.683901,((x5 * x5) + x0) * -1.0805811

best: x0*(-1.4503202) + x5*(-0.999171)*x5 + sin(x0 + x1*1.9893309)*2.163329

### Konfiguracja 2 z operatorem `p` (szum 0.5)

In [48]:
model2_p_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model2_p_n05.fit(X_p_n05, y_p_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 3.320e+05
Progress: 1876 / 5000 total iterations (37.520%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.901
3           5.186e+01  3.052e-02  y = -8.8527 - x₀
4           5.090e+01  1.859e-02  y = cos(x₅) + -11.72
5           5.818e+00  2.169e+00  y = -4.3043 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.904e-03  y = (-0.3638 - (x₅ * x₅)) - safe_pow(x₀, 1.213)
10          2.845e+00  9.705e-03  y = ((sin(x₀) + -1.2747) - (x₅ * x₅)) - x₀
11          2.831e+00  5.017e-03  y = (sin(sin(x₀)) - (x₅ * x₅)) + (-1.269 - x₀)
12          2.751e+00  2.860e-02  y = (((sin(x₁) * 0.21441) - x₅) * x₅) - safe_pow(x₀, 1.270...
                                      1)
13          2.716e+00  1.280e-02  y = -1.269 + ((sin(x₀ - sin(x₁)) - (x₅ * x₅)) - x₀)
14          1.249e+00  7.766e-01  y = (sin(x₀ + (x₁ + x₁)) - (x₅ * x₅)) - safe_pow(x₀, 1.268...
                                      3)
16          1.208e+00  1.687e-02  y = (sin(x₁ + (x₀ + x₁)) - (x₅ * x₅)) - (safe_pow(x₀, 1.22...
                                      07) - -0.3576)
18          1.191e+00  7.126e-03  y = ((sin((x₁ + x₀) + x₁) - (x₅ * x₅)) - (safe_pow(x₀, 1.4...
                                      839) * 0.61474)) + -0.94862
21          1.144e+00  1.329e-02  y = (sin(x₀ - 0.29182) + (cos(x₀ - (1.5516 - (x₁ + x₁))) -...
                                       (x₅ * x₅))) - (x₀ + 1.447)
22          5.667e-01  7.026e-01  y = ((cos(((x₀ + x₁) + (x₁ + x₀)) - (x₀ + 1.5573)) * 2.168...
                                      2) - (x₅ * x₅)) - (x₀ * 1.4474)
24          5.281e-01  3.535e-02  y = ((cos(x₁ + ((x₁ + (x₀ + x₀)) - (x₀ + 1.5521))) * 2.168...
                                      4) - (x₅ * x₅)) - (safe_pow(x₀, 1.2297) + 0.3465)
25          4.941e-01  6.646e-02  y = (sin(x₀) - (x₀ + 1.3375)) + ((cos((x₀ + ((x₁ + x₀) + x...
                                      ₁)) - (x₀ + 1.5495)) * 2.1702) - (x₅ * x₅))
27          4.760e-01  1.867e-02  y = sin(x₀ - 0.29182) + (((cos(x₀ + (1.5516 - (((x₀ + x₀) ...
                                      + x₁) + x₁))) * 2.1537) - (x₅ * x₅)) - (x₀ + 1.447))
28          4.743e-01  3.497e-03  y = ((sin(sin(x₀ - 0.29182)) + (cos(x₀ + (1.5516 - (((x₀ +...
                                       x₀) + x₁) + x₁))) * 2.1537)) - (x₅ * x₅)) - (x₀ + 1.447)
29          4.742e-01  1.959e-04  y = ((sin(sin(x₀ - sin(0.29182))) + (cos(x₀ + (1.5516 - ((...
                                      (x₀ + x₀) + x₁) + x₁))) * 2.1537)) - (x₅ * x₅)) - (x₀ + 1....
                                      447)
30          4.737e-01  1.047e-03  y = (((sin(sin(x₀ - 0.29182)) + (cos(x₀ + (x₁ + ((x₁ + x₀)...
                                       - (1.5516 + x₀)))) * 2.1537)) - (x₅ * x₅)) * 1.0032) - (x...
                                      ₀ + 1.447)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 3.720e+05
Progress: 4209 / 5000 total iterations (84.180%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.901
3           5.186e+01  3.052e-02  y = -8.8527 - x₀
4           5.090e+01  1.859e-02  y = cos(x₅) + -11.72
5           5.818e+00  2.169e+00  y = -4.3042 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.904e-03  y = (-0.3638 - (x₅ * x₅)) - safe_pow(x₀, 1.213)
10          2.731e+00  5.076e-02  y = (0.025957 - (x₅ * x₅)) - p(x₀ + -0.49656)
12          2.631e+00  1.867e-02  y = (sin(x₁ * -2.0868) - (x₅ * x₅)) - safe_pow(x₀, 1.2701)
13          2.621e+00  3.849e-03  y = (sin(sin(x₁ * -2.0868)) - (x₅ * x₅)) - safe_pow(x₀, 1....
                                      2701)
14          1.247e+00  7.426e-01  y = (sin(x₁ + (x₀ + x₁)) - (x₅ * x₅)) - (x₀ * 1.4338)
16          1.208e+00  1.596e-02  y = (sin((x₀ + x₁) + x₁) - (x₅ * x₅)) - (safe_pow(x₀, 1.22...
                                      07) - -0.35712)
18          5.667e-01  3.784e-01  y = ((cos((x₁ + (x₀ + 11.009)) + x₁) * 2.1682) - (x₅ * x₅)...
                                      ) - (x₀ * 1.4474)
20          5.281e-01  3.535e-02  y = ((cos(x₁ + ((x₁ + 7.8726) + x₀)) * -2.1684) - (x₅ * x₅...
                                      )) - (safe_pow(x₀, 1.2297) + 0.34615)
22          5.140e-01  1.346e-02  y = (-1.6444 - safe_pow(x₀ + -1.0001, 1.303)) + ((cos(x₁ +...
                                       ((x₁ + x₀) + 7.8747)) * -2.1556) - (x₅ * x₅))
24          5.125e-01  1.484e-03  y = (((cos(x₁ + ((x₀ + x₁) + 7.8747)) * -2.1556) - ((x₅ - ...
                                      0.012981) * x₅)) - safe_pow(x₀ + -1.0001, 1.303)) + -1.644...
                                      4
25          4.941e-01  3.657e-02  y = (sin(x₀) + ((cos(((((x₀ + 1.592) + x₀) + x₁) + x₁) - x...
                                      ₀) * -2.1701) - (x₅ * x₅))) - (x₀ + 1.3374)
26          4.881e-01  1.215e-02  y = (sin(sin(x₀)) - (x₀ + 1.3338)) + ((cos((((x₀ + x₀) + 1...
                                      .589) + x₁) + (x₁ - x₀)) * -2.166) - (x₅ * x₅))
27          4.754e-01  2.642e-02  y = sin(x₀ - 0.29233) + (((cos((x₁ + (x₀ + x₀)) + (x₁ - (x...
                                      ₀ + 1.5514))) * 2.1573) - (x₅ * x₅)) - (x₀ + 1.4714))
28          4.739e-01  3.233e-03  y = sin(sin(x₀ - 0.25088)) + (((cos((1.5537 - (((x₀ + x₀) ...
                                      + x₁) + x₁)) + x₀) * 2.1563) - (x₅ * x₅)) - (x₀ + 1.4351))
30          4.602e-01  1.461e-02  y = (((cos(x₀ + (1.5624 - (x₁ + (x₁ + (x₀ + x₀))))) * 2.15...
                                      13) - (x₅ * x₅)) - (x₀ + 1.5402)) + sin(x₀ - sin(x₀ - 0.87...
                                      228))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.901
3           5.186e+01  3.052e-02  y = -8.8527 - x₀
4           5.090e+01  1.859e-02  y = cos(x₅) + -11.72
5           5.818e+00  2.169e+00  y = -4.3042 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.904e-03  y = (-0.3638 - (x₅ * x₅)) - safe_pow(x₀, 1.213)
10          2.731e+00  5.076e-02  y = (0.025957 - (x₅ * x₅)) - p(x₀ + -0.49656)
12          2.616e+00  2.156e-02  y = (sin(x₁ * -2.0141) - (x₅ * x₅)) - safe_pow(x₀, 1.2705)
14          1.247e+00  3.704e-01  y = (sin(x₁ + (x₀ + x₁)) - (x₅ * x₅)) - (x₀ * 1.4338)
16          1.208e+00  1.596e-02  y = (sin((x₀ + x₁) + x₁) - (x₅ * x₅)) - (safe_pow(x₀, 1.22...
                                      07) - -0.35712)
17          1.177e+00  2.622e-02  y = (sin(x₁ + (x₀ + x₁)) - (x₅ * x₅)) + (sin(x₀) - (x₀ + 1...
                                      .3052))
18          5.667e-01  7.305e-01  y = ((cos((x₁ + (x₀ + 11.009)) + x₁) * 2.1682) - (x₅ * x₅)...
                                      ) - (x₀ * 1.4474)
20          5.281e-01  3.535e-02  y = ((cos(x₁ + ((x₁ + 7.8726) + x₀)) * -2.1684) - (x₅ * x₅...
                                      )) - (safe_pow(x₀, 1.2297) + 0.34615)
22          5.140e-01  1.346e-02  y = (-1.6444 - safe_pow(x₀ + -1.0001, 1.303)) + ((cos(x₁ +...
                                       ((x₁ + x₀) + 7.8747)) * -2.1556) - (x₅ * x₅))
24          5.125e-01  1.494e-03  y = (((-2.153 * cos(((x₀ + 1.5881) + x₁) + x₁)) - ((x₅ - 0...
                                      .013838) * x₅)) - safe_pow(x₀ + -1.0008, 1.3032)) + -1.646...
                                      2
25          4.941e-01  3.655e-02  y = (sin(x₀) + ((cos((x₁ + (((x₀ + 1.5921) + x₀) + x₁)) - ...
                                      x₀) * -2.1702) - (x₅ * x₅))) - (x₀ + 1.3375)
26          4.881e-01  1.215e-02  y = (sin(sin(x₀)) - (x₀ + 1.3338)) + ((cos((((x₀ + x₀) + 1...
                                      .589) + x₁) + (x₁ - x₀)) * -2.166) - (x₅ * x₅))
27          4.754e-01  2.642e-02  y = sin(x₀ - 0.29233) + (((cos((x₁ + (x₀ + x₀)) + (x₁ - (x...
                                      ₀ + 1.5514))) * 2.1573) - (x₅ * x₅)) - (x₀ + 1.4714))
28          4.739e-01  3.233e-03  y = sin(sin(x₀ - 0.25088)) + (((cos((1.5537 - (((x₀ + x₀) ...
                                      + x₁) + x₁)) + x₀) * 2.1563) - (x₅ * x₅)) - (x₀ + 1.4351))
30          4.602e-01  1.461e-02  y = (((cos(x₀ + (1.5624 - (x₁ + (x₁ + (x₀ + x₀))))) * 2.15...
                                      13) - (x₅ * x₅)) - (x₀ + 1.5402)) + sin(x₀ - sin(x₀ - 0.87...
                                      228))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143215_5UmtJH/hall_of_fame.csv

In [49]:
show_results(model2_p_n05)

,complexity,loss,score,equation
3,5,5.818119,2.168934,-4.304165 - (x5 * x5)
11,18,0.566741,0.730512,((cos((x1 + (x0 + 11.008982)) + x1) * 2.168232...
8,14,1.247065,0.370354,(sin(x1 + (x0 + x1)) - (x5 * x5)) - (x0 * 1.43...

best: -1.4474493*x0 - x5*x5 + cos(x0 + x1 + x1 + 11.008982)*2.1682327

### Konfiguracja 3 z operatorem `p` (szum 0.5)

In [50]:
model3_p_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model3_p_n05.fit(X_p_n05, y_p_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

Expressions evaluated per second: 7.510e+05
Progress: 4398 / 5000 total iterations (87.960%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.903
3           5.186e+01  3.052e-02  y = -8.8524 - x₀
5           5.818e+00  1.094e+00  y = -4.3042 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.938e-03  y = (safe_pow(1.4261, x₀) * -1.3501) - (x₅ * x₅)
10          2.795e+00  2.758e-02  y = ((sin(x₀) + -1.8874) * 2.3046) - (x₅ * x₅)
12          2.642e+00  2.812e-02  y = sin(x₁ * -1.9981) - ((x₅ * x₅) - (x₀ * -1.4343))
13          2.627e+00  5.676e-03  y = sin(sin(x₁ * -1.9896)) - ((x₅ * x₅) - (x₀ * -1.4334))
14          8.192e-01  1.165e+00  y = ((sin((x₁ + x₀) + x₁) - x₀) * 1.4727) - (x₅ * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.903
3           5.186e+01  3.052e-02  y = -8.8524 - x₀
5           5.818e+00  1.094e+00  y = -4.3042 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.938e-03  y = (safe_pow(1.4261, x₀) * -1.3501) - (x₅ * x₅)
10          2.795e+00  2.758e-02  y = ((sin(x₀) + -1.8874) * 2.3046) - (x₅ * x₅)
12          2.642e+00  2.812e-02  y = sin(x₁ * -1.9981) - ((x₅ * x₅) - (x₀ * -1.4343))
13          2.627e+00  5.676e-03  y = sin(sin(x₁ * -1.9896)) - ((x₅ * x₅) - (x₀ * -1.4334))
14          8.192e-01  1.165e+00  y = ((sin(x₀ + (x₁ + x₁)) - x₀) * 1.4727) - (x₅ * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143227_BxYIBa/hall_of_fame.csv

In [51]:
show_results(model3_p_n05)

,complexity,loss,score,equation
8,14,0.819225,1.165212,((sin(x0 + (x1 + x1)) - x0) * 1.4726788) - (x5...
2,5,5.818119,1.093766,-4.304165 - (x5 * x5)
3,7,2.913032,0.345891,(x0 * -1.4216827) - (x5 * x5)

best: -x5*x5 + (-x0 + sin(x0 + x1 + x1))*1.4726788

### 5.0 — Zakres [-15, 15], szum $\sigma=2$

In [52]:
X_p_w2, y_p_w2 = make_data_prime(-15, 15, noise_std=2)

### Konfiguracja 1 z operatorem `p` (zakres [-15,15], σ=2)

In [53]:
model1_p_w2 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p_w2.fit(X_p_w2, y_p_w2)

Expressions evaluated per second: 3.160e+05
Progress: 1486 / 5000 total iterations (29.720%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.21
3           4.632e+03  1.532e-04  y = x₂ + -95.436
4           4.624e+03  1.210e-03  y = sin(x₂) + -95.208
5           3.854e+02  2.485e+00  y = (x₅ * x₅) * -1.1556
7           1.546e+02  4.566e-01  y = ((x₅ * x₅) + x₀) * -1.0969
8           9.320e+00  2.809e+00  y = (p(x₀) + (x₅ * x₅)) * -0.989
10          6.523e+00  1.784e-01  y = (p(x₀ + -0.50809) + (x₅ * x₅)) * -1.0011
12          6.464e+00  4.576e-03  y = ((x₅ * (x₅ + -0.037805)) + p(-0.50751 + x₀)) * -1.001
14          6.464e+00  8.941e-08  y = ((x₅ * x₅) + ((x₅ * -0.037805) + p(x₀ + -0.50751))) * ...
                                      -1.001
15          6.410e+00  8.360e-03  y = (sin(x₄ * -0.50818) + ((x₅ * x₅) + p(x₀ + -0.50818))) ...
                                      * -1.0012
16          6.372e+00  5.911e-03  y = (sin(sin(x₄ * -0.50818)) + ((x₅ * x₅) + p(x₀ + -0.5081...
                                      8))) * -1.0012
17          6.179e+00  3.076e-02  y = (sin((x₁ * -0.21073) * x₅) + (p(x₀ + -0.50818) + (x₅ *...
                                       x₅))) * -1.0012
18          6.162e+00  2.780e-03  y = (sin(sin((x₁ * -0.2108) * x₅)) + (p(x₀ + -0.50773) + (...
                                      x₅ * x₅))) * -1.0012
19          6.159e+00  5.607e-04  y = (sin(sin(sin((x₅ * x₁) * -0.21081))) + (p(x₀ + -0.5076...
                                      ) + (x₅ * x₅))) * -1.0012
20          6.152e+00  1.158e-03  y = ((sin(sin(x₅ * (-0.2108 * x₁))) + (p(-0.50773 + x₀) + ...
                                      (x₅ * x₅))) * -1.0012) + -0.12762
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 2.590e+05
Progress: 2706 / 5000 total iterations (54.120%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.21
3           4.632e+03  1.532e-04  y = x₂ + -95.436
4           4.624e+03  1.210e-03  y = sin(x₂) + -95.208
5           3.854e+02  2.485e+00  y = (x₅ * x₅) * -1.1556
7           1.546e+02  4.566e-01  y = ((x₅ * x₅) + x₀) * -1.0969
8           9.320e+00  2.809e+00  y = (p(x₀) + (x₅ * x₅)) * -0.989
10          6.523e+00  1.784e-01  y = ((x₅ * x₅) + p(x₀ + -0.50922)) * -1.0011
12          6.458e+00  4.998e-03  y = (p(x₀ + -0.50747) + (x₅ * (x₅ + -0.029626))) * -1.0013
14          6.432e+00  2.076e-03  y = ((x₅ * (x₅ + -0.028231)) + (p(x₀ + -0.50977) + 0.23393...
                                      )) * -0.99958
15          6.397e+00  5.368e-03  y = ((p(x₀ + -0.50754) + (x₅ * x₅)) + sin(x₄ * -0.48658)) ...
                                      * -1.0013
16          6.244e+00  2.422e-02  y = (p(x₀ + -0.50805) + ((x₅ * x₅) + sin(exp(x₅ * -1.0012)...
                                      ))) * -1.0012
17          6.103e+00  2.292e-02  y = (sin((x₅ * 1.8198) * x₁) + (p(x₀ + -0.50747) + (x₅ * x...
                                      ₅))) * -1.0008
18          6.095e+00  1.207e-03  y = (((x₅ * x₅) + p(x₀ + -0.50747)) + sin(sin(x₁ * (1.8198...
                                       * x₅)))) * -1.0011
19          6.078e+00  2.770e-03  y = (((sin((x₁ * x₅) * 1.8171) + (x₅ * x₅)) + p(x₀ + -0.50...
                                      756)) * -0.99953) + -0.20978
20          6.068e+00  1.724e-03  y = ((sin(sin(x₅ * (x₁ * 1.8171))) + ((x₅ * x₅) + p(x₀ + -...
                                      0.50758))) * -0.99953) + -0.20978
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 2.370e+05
Progress: 3779 / 5000 total iterations (75.580%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.21
3           4.632e+03  1.532e-04  y = x₂ + -95.436
4           4.624e+03  1.210e-03  y = sin(x₂) + -95.208
5           3.854e+02  2.485e+00  y = (x₅ * x₅) * -1.1556
7           1.546e+02  4.566e-01  y = ((x₅ * x₅) + x₀) * -1.0969
8           9.320e+00  2.809e+00  y = (p(x₀) + (x₅ * x₅)) * -0.989
10          6.523e+00  1.784e-01  y = ((x₅ * x₅) + p(x₀ + -0.50922)) * -1.0011
12          6.458e+00  4.998e-03  y = (p(x₀ + -0.50747) + (x₅ * (x₅ + -0.029626))) * -1.0013
14          6.431e+00  2.105e-03  y = (p(x₀ + -0.50904) + (0.31696 + ((x₅ + -0.028235) * x₅)...
                                      )) * -0.99888
15          6.250e+00  2.853e-02  y = sin(x₃ * -2.2109) + ((p(-0.50746 + x₀) + (x₅ * x₅)) * ...
                                      -1.0008)
16          6.163e+00  1.403e-02  y = (sin(exp(x₅ * -1.0012)) + ((x₅ * x₅) + p(x₀ + -0.50803...
                                      ))) * -1.0012
17          6.103e+00  9.895e-03  y = (sin((x₁ * 1.8198) * x₅) + ((x₅ * x₅) + p(x₀ + -0.5074...
                                      6))) * -1.0008
18          6.095e+00  1.208e-03  y = ((p(x₀ + -0.50746) + (x₅ * x₅)) + sin(sin((x₅ * 1.8198...
                                      ) * x₁))) * -1.0011
19          6.078e+00  2.775e-03  y = (((x₅ * x₅) + (sin(x₁ * (x₅ * 1.8171)) + p(x₀ + -0.507...
                                      51))) * -0.99954) + -0.20978
20          6.066e+00  1.988e-03  y = -1.0008 * ((p(x₀ + -0.50746) + (x₅ * x₅)) + sin(((x₁ *...
                                       1.8198) * x₅) + exp(-1.3247)))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.21
3           4.632e+03  1.532e-04  y = x₂ + -95.436
4           4.624e+03  1.210e-03  y = sin(x₂) + -95.208
5           3.854e+02  2.485e+00  y = (x₅ * x₅) * -1.1556
7           1.546e+02  4.566e-01  y = ((x₅ * x₅) + x₀) * -1.0969
8           9.320e+00  2.809e+00  y = (p(x₀) + (x₅ * x₅)) * -0.989
10          6.523e+00  1.784e-01  y = ((x₅ * x₅) + p(x₀ + -0.50922)) * -1.0011
12          6.458e+00  4.998e-03  y = (p(x₀ + -0.50747) + (x₅ * (x₅ + -0.029626))) * -1.0013
14          6.431e+00  2.145e-03  y = (((x₅ + -0.028239) * x₅) + (p(x₀ + -0.50758) + 0.28873...
                                      )) * -0.99919
15          6.250e+00  2.845e-02  y = sin(x₃ * -2.2109) + ((p(-0.50746 + x₀) + (x₅ * x₅)) * ...
                                      -1.0008)
16          6.163e+00  1.407e-02  y = (sin(exp(-1.0012 * x₅)) + ((x₅ * x₅) + p(x₀ + -0.50803...
                                      ))) * -1.0012
17          6.103e+00  9.855e-03  y = -1.0008 * (sin((1.8198 * x₅) * x₁) + (p(-0.50746 + x₀)...
                                       + (x₅ * x₅)))
18          6.095e+00  1.207e-03  y = ((p(x₀ + -0.50746) + (x₅ * x₅)) + sin(sin((x₅ * 1.8198...
                                      ) * x₁))) * -1.0011
19          6.016e+00  1.302e-02  y = (sin(x₁ * (x₅ * 1.8181)) + (p(x₀ + -0.50754) + (x₅ * (...
                                      x₅ + -0.032937)))) * -1.0009
───────────────────────────────────────────────────────────────────────────────────────────────────

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143234_PEDQBo/hall_of_fame.csv

In [54]:
show_results(model1_p_w2)

   complexity        loss     score                           equation
5           8    9.319632  2.808837  (p(x0) + (x5 * x5)) * -0.98899573
3           5  385.373080  2.484887             (x5 * x5) * -1.1555504
4           7  154.618360  0.456626      ((x5 * x5) + x0) * -1.0968556

best: (x5*x5 + sympy_p(x0 - 0.50922304))*(-1.0011047)

### Konfiguracja 2 z operatorem `p` (zakres [-15,15], σ=2)

In [55]:
model2_p_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model2_p_w2.fit(X_p_w2, y_p_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Expressions evaluated per second: 2.710e+05
Progress: 1364 / 5000 total iterations (27.280%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.118 - x₀
5           1.952e+02  1.573e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7182) - (x₅ * x₅)
8           8.644e+00  6.427e-01  y = (p(x₀) * -0.94168) - (x₅ * x₅)
10          6.481e+00  1.440e-01  y = (x₅ * (0.035163 - x₅)) - p(x₀ + -0.50753)
12          6.434e+00  3.662e-03  y = (x₅ * (0.030038 - x₅)) + (-0.20386 - p(x₀ + -0.50747))
14          6.095e+00  2.702e-02  y = (sin(p(x₀ - -0.43871)) - p(x₀ + -0.5084)) - (x₅ * x₅)
15          6.087e+00  1.424e-03  y = (sin(p(x₀ - sin(-0.46929))) - p(x₀ + -0.5084)) - (x₅ *...
                                       x₅)
17          6.061e+00  2.116e-03  y = ((sin(p(x₀ - sin(-0.46929))) - p(x₀ + -0.5084)) - -0.1...
                                      6679) - (x₅ * x₅)
18          6.054e+00  1.180e-03  y = (sin(p(x₀ - -0.43871)) - p(x₀ + -0.5084)) - (x₅ * (x₅ ...
                                      + (0.39742 - 0.40736)))
20          6.028e+00  2.105e-03  y = ((sin(p(x₀ - -0.43871)) - p(x₀ + -0.5084)) - (x₅ * ((x...
                                      ₅ + 0.39742) - 0.40736))) - -0.11553
27          6.017e+00  2.659e-04  y = ((0.027599 - x₅) * x₅) - (cos(exp((1.9394 - exp(cos((p...
                                      (x₀ - -0.53816) + -0.71066) - 0.7777))) + 0.25639)) + p(x₀...
                                       + -0.50758))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 2.050e+05
Progress: 2163 / 5000 total iterations (43.260%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.118 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7182) - (x₅ * x₅)
8           8.644e+00  6.427e-01  y = (p(x₀) * -0.94168) - (x₅ * x₅)
10          6.478e+00  1.442e-01  y = ((0.027599 - x₅) * x₅) - p(x₀ + -0.50758)
12          6.434e+00  3.445e-03  y = (x₅ * (0.030038 - x₅)) + (-0.20386 - p(x₀ + -0.50747))
14          6.095e+00  2.702e-02  y = (sin(p(x₀ - -0.43871)) - p(x₀ + -0.5084)) - (x₅ * x₅)
15          6.087e+00  1.424e-03  y = (sin(p(x₀ - sin(-0.46929))) - p(x₀ + -0.5084)) - (x₅ *...
                                       x₅)
16          6.061e+00  4.138e-03  y = (0.18511 - (x₅ * x₅)) + (sin(p(x₀ - -0.45225)) - p(x₀ ...
                                      + -0.5084))
17          6.061e+00  9.275e-05  y = ((sin(p(x₀ - sin(-0.46929))) - p(x₀ + -0.5084)) - -0.1...
                                      6679) - (x₅ * x₅)
18          5.988e+00  1.207e-02  y = ((sin(p(x₀ - -0.41396)) + 0.13943) - p(x₀ + -0.50755))...
                                       - (x₅ * (x₅ + -0.03727))
20          5.987e+00  1.228e-04  y = (sin(p(x₀ - -0.43871) + -0.1432) - p(x₀ + -0.5084)) - ...
                                      ((x₅ * (x₅ + -0.042381)) + -0.12602)
22          5.967e+00  1.658e-03  y = -0.5075 + ((sin(p(x₀ - -0.43877)) - p(-0.5075 + x₀)) -...
                                       ((x₅ * (x₅ + -0.022342)) - cos(cos(x₄))))
23          5.838e+00  2.190e-02  y = sin(((x₃ * x₀) + -0.71228) * 1.0694) + ((sin(p(x₀ - -0...
                                      .4186)) - p(x₀ + -0.50749)) - (x₅ * x₅))
24          5.825e+00  2.140e-03  y = (((((x₄ * x₃) * -0.00074857) - (x₅ + -0.040025)) * x₅)...
                                       + -0.0021897) + (sin(p(x₀ - -0.4186)) - p(x₀ + -0.53428))
25          5.746e+00  1.377e-02  y = sin((-0.71228 + (x₃ * x₀)) * 1.0694) + ((sin(p(x₀ - -0...
                                      .4186)) - p(x₀ + -0.50749)) - ((x₅ + -0.038431) * x₅))
26          5.730e+00  2.786e-03  y = ((sin((x₀ * (1.0694 * x₃)) + cos(x₀)) + sin(p(x₀ - -0....
                                      4186))) - p(-0.50749 + x₀)) - ((x₅ + -0.038431) * x₅)
27          5.713e+00  2.927e-03  y = sin((x₃ * (x₀ * 1.0694)) + -0.71228) + ((sin(p(x₀ - -0...
                                      .4186)) - p(x₀ + -0.50749)) - (((x₅ + -0.038431) * x₅) - 0...
                                      .19743))
28          5.707e+00  1.045e-03  y = (((sin((x₀ * (1.0694 * x₃)) + cos(x₀)) + sin(p(x₀ - -0...
                                      .4186))) - p(-0.50749 + x₀)) - ((x₅ + -0.038431) * x₅)) + ...
                                      0.078972
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 2.020e+05
Progress: 3222 / 5000 total iterations (64.440%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.118 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7182) - (x₅ * x₅)
8           8.644e+00  6.427e-01  y = (p(x₀) * -0.94168) - (x₅ * x₅)
10          6.478e+00  1.442e-01  y = ((0.028314 - x₅) * x₅) - p(-0.50746 + x₀)
12          6.434e+00  3.444e-03  y = (((0.028314 - x₅) * x₅) + -0.20719) - p(-0.50746 + x₀)
14          6.087e+00  2.772e-02  y = (sin(p(x₀ - -0.45214)) - p(-0.5084 + x₀)) - (x₅ * x₅)
15          5.037e+00  1.893e-01  y = (sin((x₁ + x₁) + x₀) - p(x₀ + -0.50749)) - (x₅ * x₅)
17          4.542e+00  5.171e-02  y = ((2.111 * sin((x₁ + x₁) + x₀)) - p(-0.50783 + x₀)) - (...
                                      x₅ * x₅)
19          4.503e+00  4.277e-03  y = (sin((x₁ + x₁) + x₀) * 2.111) + ((-0.1501 - p(x₀ + -0....
                                      50783)) - (x₅ * x₅))
21          4.495e+00  9.417e-04  y = (((sin((x₁ + x₁) + x₀) * (2.111 + -0.1501)) - p(x₀ + -...
                                      0.50783)) - (x₅ * x₅)) + -0.20355
22          4.494e+00  9.132e-05  y = ((-0.1501 - p(x₀ + -0.50783)) - (x₅ * x₅)) + ((sin((x₁...
                                       + x₁) + x₀) * p(1.0655)) - 0.071703)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 2.000e+05
Progress: 4335 / 5000 total iterations (86.700%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.118 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7182) - (x₅ * x₅)
8           8.644e+00  6.427e-01  y = (p(x₀) * -0.94168) - (x₅ * x₅)
10          6.478e+00  1.442e-01  y = ((0.028314 - x₅) * x₅) - p(-0.50746 + x₀)
12          6.434e+00  3.444e-03  y = (((0.028314 - x₅) * x₅) + -0.20719) - p(-0.50746 + x₀)
13          6.426e+00  1.122e-03  y = (sin(x₄ * 0.50102) - p(x₀ + -0.50755)) - (x₅ * x₅)
14          6.087e+00  5.433e-02  y = (sin(p(x₀ - -0.45214)) - p(-0.5084 + x₀)) - (x₅ * x₅)
15          5.037e+00  1.893e-01  y = (sin((x₁ + x₁) + x₀) - p(x₀ + -0.50749)) - (x₅ * x₅)
17          4.536e+00  5.239e-02  y = ((sin((x₁ + x₀) + x₁) * 2) - p(x₀ + -0.50783)) - (x₅ *...
                                       x₅)
19          4.458e+00  8.612e-03  y = ((sin(x₀ + ((x₁ + x₁) * 0.99123)) * 2.0115) - p(x₀ + -...
                                      0.50755)) - (x₅ * x₅)
21          4.402e+00  6.317e-03  y = ((sin(((x₁ + x₁) * 0.98668) + x₀) * 2.0115) - p(x₀ + -...
                                      0.50751)) - ((x₅ * x₅) + 0.22235)
24          4.346e+00  4.264e-03  y = (((sin(x₀) + 1.9538) * sin(x₀ + ((x₁ + x₁) * 0.98389))...
                                      ) - p(x₀ + -0.50763)) - ((x₅ * x₅) - -0.206)
28          4.284e+00  3.625e-03  y = ((sin(x₀ + ((x₁ + x₁) * 0.99122)) * (cos(x₁ + safe_pow...
                                      (1.2211, x₄)) + 2.0115)) - p(x₀ + -0.50749)) + (-0.27321 -...
                                       (x₅ * x₅))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.118 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7182) - (x₅ * x₅)
8           8.644e+00  6.427e-01  y = (p(x₀) * -0.94168) - (x₅ * x₅)
10          6.478e+00  1.442e-01  y = ((0.028314 - x₅) * x₅) - p(-0.50746 + x₀)
12          6.434e+00  3.444e-03  y = (((0.028314 - x₅) * x₅) + -0.20719) - p(-0.50746 + x₀)
13          6.370e+00  9.990e-03  y = (cos(x₀ * x₂) - p(x₀ + -0.50749)) - (x₅ * x₅)
14          6.087e+00  4.546e-02  y = (sin(p(x₀ - -0.45214)) - p(-0.5084 + x₀)) - (x₅ * x₅)
15          5.037e+00  1.893e-01  y = (sin((x₁ + x₁) + x₀) - p(x₀ + -0.50749)) - (x₅ * x₅)
17          4.536e+00  5.239e-02  y = ((sin((x₁ + x₀) + x₁) * 2) - p(x₀ + -0.50783)) - (x₅ *...
                                       x₅)
19          4.458e+00  8.616e-03  y = ((sin(((x₁ + x₁) * 0.99122) + x₀) * 2.0115) - p(x₀ + -...
                                      0.50748)) - (x₅ * x₅)
21          4.402e+00  6.313e-03  y = ((sin(((x₁ + x₁) * 0.98668) + x₀) * 2.0115) - p(x₀ + -...
                                      0.50751)) - ((x₅ * x₅) + 0.22235)
22          4.388e+00  3.270e-03  y = (((1.9538 + sin(x₀)) * sin(x₀ + ((x₁ + x₁) * 0.98391))...
                                      ) - p(-0.5076 + x₀)) - (x₅ * x₅)
23          4.199e+00  4.413e-02  y = (((sin((x₁ + x₁) + x₀) * 1.7383) - (x₅ * x₅)) + cos(ex...
                                      p(safe_pow(0.94687, x₄)))) - p(x₀ + -0.50747)
24          4.173e+00  6.053e-03  y = (cos(exp(safe_pow(0.94688, x₄))) - p(-0.50749 + x₀)) +...
                                       ((sin((x₁ + x₁) + x₀) * p(0.85781)) - (x₅ * x₅))
25          4.109e+00  1.549e-02  y = ((sin(((x₁ + x₁) * 0.99122) + x₀) * 1.9334) - (x₅ * x₅...
                                      )) + (cos(exp(safe_pow(0.94688, x₄))) - p(x₀ + -0.50749))
27          4.109e+00  3.812e-05  y = ((sin(x₀ + (x₁ + (x₁ * 0.9773))) * 2.0113) + (cos(exp(...
                                      safe_pow(0.94547, x₄))) - (p(x₀ + -0.50563) + -0.14019))) ...
                                      - (x₅ * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143254_dPilg4/hall_of_fame.csv

In [56]:
show_results(model2_p_w2)

   complexity        loss     score                          equation
3           5  195.229480  3.120413            -20.770073 - (x5 * x5)
4           7   16.436457  1.237337     (x0 * -2.7182167) - (x5 * x5)
5           8    8.643805  0.642659  (p(x0) * -0.9416777) - (x5 * x5)

best: -x5*x5 - sympy_p(x0 - 0.50749236) + sin(x0 + x1 + x1)

### Konfiguracja 3 z operatorem `p` (zakres [-15,15], σ=2)

In [57]:
model3_p_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model3_p_w2.fit(X_p_w2, y_p_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Expressions evaluated per second: 4.690e+05
Progress: 2706 / 5000 total iterations (54.120%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.119 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7181) - (x₅ * x₅)
8           8.646e+00  6.424e-01  y = (p(x₀) * -0.94005) - (x₅ * x₅)
10          6.478e+00  1.443e-01  y = (x₅ * (0.02888 - x₅)) - p(x₀ + -0.50889)
12          6.434e+00  3.409e-03  y = (-0.19421 - p(x₀ - 0.50795)) - (x₅ * (x₅ - 0.030611))
14          6.127e+00  2.443e-02  y = (sin(p(x₀ - -0.57184)) - p(x₀ - 0.50747)) - (x₅ * x₅)
15          6.088e+00  6.429e-03  y = (sin(p(x₀ - sin(-2.6805))) - p(x₀ + -0.50889)) - (x₅ *...
                                       x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.206
3           4.540e+03  1.017e-02  y = -87.119 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           1.644e+01  1.237e+00  y = (x₀ * -2.7181) - (x₅ * x₅)
8           8.644e+00  6.427e-01  y = (p(x₀) * -0.94168) - (x₅ * x₅)
10          6.478e+00  1.442e-01  y = (x₅ * (0.02888 - x₅)) - p(x₀ + -0.50889)
12          6.426e+00  4.067e-03  y = (-0.66544 - (p(x₀ - 0.50757) * 0.97803)) - (x₅ * x₅)
13          6.327e+00  1.552e-02  y = (sin(x₀ * -2.9292) - p(x₀ + -0.50889)) - (x₅ * x₅)
14          6.088e+00  3.844e-02  y = (sin(p(x₀ - -0.44493)) - p(x₀ + -0.50889)) - (x₅ * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143317_ex3135/hall_of_fame.csv

In [58]:
show_results(model3_p_w2)

   complexity        loss     score                          equation
3           5  195.229480  3.120413             -20.77007 - (x5 * x5)
4           7   16.436457  1.237337     (x0 * -2.7181113) - (x5 * x5)
5           8    8.643805  0.642659  (p(x0) * -0.9416777) - (x5 * x5)

best: -x5*x5 + sympy_p(x0)*(-0.9416777)

### 5.0 — Zakres [-15, 15], szum $\sigma=5$

In [59]:
X_p_w5, y_p_w5 = make_data_prime(-15, 15, noise_std=5)

### Konfiguracja 1 z operatorem `p` (zakres [-15,15], σ=5)

In [60]:
model1_p_w5 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p_w5.fit(X_p_w5, y_p_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 3.530e+05
Progress: 1858 / 5000 total iterations (37.160%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.661e+03  4.732e-04  y = x₂ + -95.697
4           4.656e+03  4.891e-04  y = sin(x₂) + -95.469
5           4.034e+02  2.446e+00  y = x₅ * (x₅ * -1.1583)
7           1.733e+02  4.226e-01  y = (x₀ + (x₅ * x₅)) * -1.0994
8           3.152e+01  1.704e+00  y = ((x₅ * x₅) + p(x₀)) * -0.99112
10          2.885e+01  4.432e-02  y = ((x₅ * x₅) + p(x₀ * 0.95491)) * -1.0015
12          2.872e+01  2.212e-03  y = (x₅ * (x₅ * -0.99962)) + (p(x₀ + 0.38213) * -0.91233)
14          2.850e+01  3.842e-03  y = ((x₅ * (x₅ + -0.054485)) * -1.0001) + (p(x₀ + 0.38157)...
                                       * -0.9111)
16          2.834e+01  2.699e-03  y = ((p(x₀ + 0.38161) + -0.92813) * -0.93088) + ((x₅ * -1....
                                      0031) * (x₅ + -0.055087))
17          2.814e+01  7.397e-03  y = sin(x₅ * 1.4441) + ((x₅ * (x₅ * -0.99979)) + (p(x₀ + 0...
                                      .38197) * -0.91181))
18          2.788e+01  9.010e-03  y = sin(exp(x₅ * 1.4077)) + ((x₅ * (x₅ * -1.0002)) + (p(x₀...
                                       + 0.38144) * -0.91154))
20          2.784e+01  8.351e-04  y = ((sin(exp(x₅ * 1.4077)) + ((x₅ * -1.0002) * x₅)) + (p(...
                                      x₀ + 0.38144) * -0.91154)) + 0.25446
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 3.360e+05
Progress: 3491 / 5000 total iterations (69.820%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.661e+03  4.732e-04  y = x₂ + -95.697
4           4.656e+03  4.891e-04  y = sin(x₂) + -95.469
5           4.034e+02  2.446e+00  y = x₅ * (x₅ * -1.1583)
7           1.733e+02  4.226e-01  y = (x₀ + (x₅ * x₅)) * -1.0994
8           3.152e+01  1.704e+00  y = ((x₅ * x₅) + p(x₀)) * -0.99112
10          2.885e+01  4.432e-02  y = ((x₅ * x₅) + p(x₀ * 0.95491)) * -1.0015
12          2.872e+01  2.212e-03  y = ((x₅ * x₅) * -0.99967) + (p(x₀ + 0.38181) * -0.91232)
14          2.850e+01  3.842e-03  y = ((x₅ * (x₅ + -0.054485)) * -1.0001) + (p(x₀ + 0.38157)...
                                       * -0.9111)
15          2.849e+01  2.641e-04  y = ((p(x₀ + 0.3815) + cos(x₀)) * -0.90529) + (x₅ * (x₅ * ...
                                      -1.0012))
16          2.834e+01  5.133e-03  y = ((p(x₀ + 0.38175) * -0.93079) + ((x₅ * -1.0031) * (x₅ ...
                                      + -0.055193))) + 0.85935
17          2.772e+01  2.245e-02  y = ((p(x₀ + 0.38165) + sin(x₄ * 4.3871)) * -0.91399) + (x...
                                      ₅ * (x₅ * -0.99927))
18          2.766e+01  2.094e-03  y = ((p(x₀ + 0.38124) + sin(exp(x₅ * -1.0011))) * -0.91182...
                                      ) + ((x₅ * x₅) * -0.99977)
19          2.752e+01  4.997e-03  y = ((cos((x₃ * -0.45378) * x₅) + p(x₀ + 0.38152)) * -0.91...
                                      237) + ((x₅ * x₅) * -0.99881)
20          2.701e+01  1.858e-02  y = ((p(sin(exp(x₅ * -0.97026)) + (x₀ + 0.37963)) * -0.911...
                                      22) + (x₅ * (x₅ * -1.0005))) + 0.4527
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.661e+03  4.732e-04  y = x₂ + -95.697
4           4.656e+03  4.891e-04  y = sin(x₂) + -95.469
5           4.034e+02  2.446e+00  y = x₅ * (x₅ * -1.1583)
7           1.733e+02  4.226e-01  y = (x₀ + (x₅ * x₅)) * -1.0994
8           3.152e+01  1.704e+00  y = ((x₅ * x₅) + p(x₀)) * -0.99112
10          2.885e+01  4.432e-02  y = ((x₅ * x₅) + p(x₀ * 0.95491)) * -1.0015
12          2.872e+01  2.212e-03  y = ((x₅ * x₅) * -0.99967) + (p(x₀ + 0.38181) * -0.91232)
14          2.850e+01  3.842e-03  y = ((x₅ * (x₅ + -0.054485)) * -1.0001) + (p(x₀ + 0.38157)...
                                       * -0.9111)
15          2.849e+01  2.641e-04  y = ((p(x₀ + 0.3815) + cos(x₀)) * -0.90529) + (x₅ * (x₅ * ...
                                      -1.0012))
16          2.834e+01  5.174e-03  y = (p(x₀ + 0.38164) * -0.92944) + (cos(sin(x₁)) + (x₅ * (...
                                      x₅ * -1.0024)))
17          2.771e+01  2.244e-02  y = ((p(x₀ + 0.38152) + sin(x₄ * 4.3832)) * -0.91417) + ((...
                                      x₅ * -0.99926) * x₅)
18          2.724e+01  1.743e-02  y = (p(sin(exp(-0.97026 * x₅)) + (x₀ + 0.37963)) * -0.8871...
                                      ) + ((x₅ * -1.0005) * x₅)
20          2.699e+01  4.443e-03  y = ((p((sin(exp(x₅ * -0.97026)) + x₀) + 0.37963) * -0.911...
                                      22) + ((x₅ * -1.0005) * x₅)) + 0.58641
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260518_143327_Gm9Ss7/hall_of_fame.csv

In [61]:
show_results(model1_p_w5)

   complexity        loss     score                           equation
3           5  403.434700  2.445899             x5 * (x5 * -1.1582632)
5           8   31.519264  1.704235  ((x5 * x5) + p(x0)) * -0.99111545
4           7  173.267030  0.422590      (x0 + (x5 * x5)) * -1.0993764

best: (x5*x5 + sympy_p(x0))*(-0.99111545)

### Konfiguracja 2 z operatorem `p` (zakres [-15,15], σ=5)

In [62]:
model2_p_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
)
model2_p_w5.fit(X_p_w5, y_p_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

Expressions evaluated per second: 1.690e+05
Progress: 852 / 5000 total iterations (17.040%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.573e+03  9.902e-03  y = -87.375 - x₀
4           4.461e+03  2.440e-02  y = -73.29 - p(x₀)
5           2.109e+02  3.051e+00  y = -21.031 - (x₅ * x₅)
7           3.655e+01  8.764e-01  y = (x₀ * -2.7326) - (x₅ * x₅)
8           3.130e+01  1.551e-01  y = (1.1392 - p(x₀)) - (x₅ * x₅)
9           3.088e+01  1.356e-02  y = ((x₀ * -3.2457) - (x₅ * x₅)) - -5.2358
10          2.901e+01  6.263e-02  y = (-0.12367 - (x₅ * x₅)) - p(x₀ * 0.95615)
12          2.841e+01  1.045e-02  y = (0.569 - (x₅ * x₅)) - p((x₀ + 0.70241) * 0.90922)
14          2.831e+01  1.608e-03  y = (-0.26924 - (x₅ * x₅)) + (1.0661 - p((x₀ + 0.7377) * 0...
                                      .90803))
16          2.824e+01  1.307e-03  y = (cos(sin(x₅ * -3.0921)) - (x₅ * x₅)) - (p(x₀ + 0.38197...
                                      ) * 0.93565)
17          2.800e+01  8.434e-03  y = (sin(x₀ * x₅) - ((x₅ * x₅) + -0.55083)) - p((x₀ * 0.91...
                                      446) + 0.57555)
18          2.784e+01  6.015e-03  y = (cos(exp((-0.1406 + 0.85042) - x₂)) - (x₅ * x₅)) - (0....
                                      92772 * p(0.38216 + x₀))
19          2.781e+01  9.271e-04  y = (cos(exp(sin((1.4925 - x₃) + x₂))) - (x₅ * x₅)) - (p(0...
                                      .38216 + x₀) * 0.92772)
20          2.748e+01  1.195e-02  y = ((sin(log(x₀) * (x₅ * x₀)) - (x₅ * x₅)) - p((x₀ * 0.91...
                                      446) + 0.57555)) - -0.29994
22          2.746e+01  2.716e-04  y = (sin((x₅ * x₀) + (-0.4842 + sin(x₄))) - ((x₅ * x₅) + -...
                                      0.45795)) - p(0.57555 + (x₀ * 0.91446))
23          2.741e+01  2.108e-03  y = (sin((x₅ * x₀) + sin(sin(x₅) + x₄)) - ((x₅ * x₅) + -0....
                                      5376)) - p((0.91446 * x₀) + 0.57555)
25          2.729e+01  2.136e-03  y = ((0.52632 - sin((x₀ * x₅) * (x₅ * cos(0.18284)))) - ((...
                                      x₅ * x₅) + cos(x₀))) - p((x₀ * 0.91446) + 0.57555)
26          2.724e+01  1.611e-03  y = (cos(((x₀ * x₀) + x₀) + (x₄ + sin(x₀ * x₅))) - ((x₅ * ...
                                      x₅) + -0.45795)) - p(0.57555 + (0.91446 * x₀))
27          2.685e+01  1.464e-02  y = (sin(((x₅ * x₀) + cos((x₀ * x₀) + x₀)) + sin(x₄)) - ((...
                                      x₅ * x₅) + -0.45795)) - p(0.57555 + (0.91446 * x₀))
29          2.677e+01  1.428e-03  y = (sin(((x₅ * x₀) + sin(x₄)) + cos(-0.42068 - ((x₀ * x₀)...
                                       + x₀))) - ((x₅ * x₅) + -0.45795)) - p((x₀ * 0.91446) + 0....
                                      57555)
30          2.663e+01  5.246e-03  y = (sin(((x₅ * x₀) + sin(x₄)) + cos((x₀ * x₀) + (x₀ - sin...
                                      (x₄)))) - ((x₅ * x₅) + -0.45795)) - p(0.57555 + (x₀ * 0.91...
                                      446))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 1.620e+05
Progress: 1595 / 5000 total iterations (31.900%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.573e+03  9.902e-03  y = -87.375 - x₀
4           4.461e+03  2.440e-02  y = -73.29 - p(x₀)
5           2.109e+02  3.051e+00  y = -21.031 - (x₅ * x₅)
7           3.655e+01  8.764e-01  y = (x₀ * -2.7326) - (x₅ * x₅)
8           3.130e+01  1.551e-01  y = (1.1495 - p(x₀)) - (x₅ * x₅)
9           3.088e+01  1.356e-02  y = ((x₀ * -3.2457) - (x₅ * x₅)) - -5.2358
10          2.881e+01  6.934e-02  y = ((0.021329 - x₅) * x₅) - p(x₀ * 0.95489)
12          2.828e+01  9.243e-03  y = (0.84738 - (x₅ * x₅)) - p((x₀ * 0.87965) + 1.0272)
14          2.824e+01  7.552e-04  y = ((0.57489 - (x₅ * x₅)) + 0.51741) - p((x₀ * 0.87867) +...
                                       1.0369)
15          2.816e+01  2.836e-03  y = (cos(1.6539 * x₀) - (x₅ * x₅)) - (p(x₀ + 0.27447) * 0....
                                      91672)
16          2.769e+01  1.704e-02  y = (cos(exp(0.71151 - x₅)) - (x₅ * x₅)) - (0.92741 * p(x₀...
                                       + 0.38101))
17          2.756e+01  4.673e-03  y = ((sin(safe_pow(1.731, x₀)) - (x₅ * x₅)) + 1.3037) - p(...
                                      (x₀ * 0.87996) + 1.0331)
20          2.744e+01  1.367e-03  y = (sin((log(x₀) * x₅) * x₀) - (x₅ * x₅)) - (p((x₀ * 0.91...
                                      552) + 0.5773) - 0.50238)
22          2.691e+01  9.800e-03  y = (sin(sin(x₅ + -1.178) + (x₅ * x₀)) - ((x₅ * x₅) + -0.3...
                                      3796)) - p((x₀ * 0.91206) + 0.62425)
24          2.686e+01  9.728e-04  y = ((sin(sin(x₅ + -1.178) + (x₅ * x₀)) - ((x₅ * x₅) + 0.3...
                                      3142)) - p((0.91206 * x₀) + 0.62425)) - -0.82831
25          2.685e+01  2.293e-04  y = (exp(-1.155) + ((sin(sin(x₅ + -1.178) + (x₅ * x₀)) - (...
                                      x₅ * x₅)) - p((x₀ * 0.91206) + 0.62425))) + 0.23452
27          2.684e+01  1.751e-04  y = ((sin(-0.35399 + (exp(-1.155) + (sin(x₅ + -1.178) + (x...
                                      ₅ * x₀)))) - (x₅ * x₅)) - p((x₀ * 0.91206) + 0.62425)) - -...
                                      0.58596
29          2.675e+01  1.753e-03  y = (sin((cos(x₂ * (x₀ + (x₀ + 0.45521))) + (x₅ * x₀)) + s...
                                      in(x₄)) - ((x₅ * x₅) + -0.45795)) - p((x₀ * 0.91446) + 0.5...
                                      7555)
30          2.663e+01  4.348e-03  y = (sin(((x₅ * x₀) + sin(x₄)) + cos((x₀ * x₀) + (x₀ - sin...
                                      (x₄)))) - ((x₅ * x₅) + -0.45795)) - p(0.57555 + (x₀ * 0.91...
                                      446))
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.

Expressions evaluated per second: 1.530e+05
Progress: 2282 / 5000 total iterations (45.640%)
════════════════════════════════════════════════════════════════════════════════════════════════════

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

Error in callback _flush_stdio (for post_execute), with arguments args (),kwargs {}:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4095: unexpected end of data

In [63]:
show_results(model2_p_w5)

   complexity        loss     score                          equation
3           5  210.936940  3.051560            -21.030697 - (x5 * x5)
4           7   36.553700  0.876388     (x0 * -2.7326171) - (x5 * x5)
5           8   30.918005  0.167444  (p(x0) * -0.9218122) - (x5 * x5)

best: x0*(-2.7326171) - x5*x5
Error in callback _flush_stdio (for post_execute), with arguments args (),kwargs {}:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4095: unexpected end of data

### Konfiguracja 3 z operatorem `p` (zakres [-15,15], σ=5)

In [66]:
model3_p_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", SAFE_POW],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"safe_pow": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p, **safe_pow_sympy},
    **default_pysr_params,
    verbosity=0,
)
model3_p_w5.fit(X_p_w5, y_p_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,100
,populations,50
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'safe_pow': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,0
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,"{'p': sympy_p, 'safe_pow': <function <la...t 0x3173608b0>}"
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

Error in callback _flush_stdio (for post_execute), with arguments args (),kwargs {}:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4095: unexpected end of data

In [67]:
show_results(model3_p_w5)

   complexity       loss     score                         equation
3           5  210.93694  3.051560           -21.030697 - (x5 * x5)
4           7   36.55370  0.876388    (x0 * -2.7326171) - (x5 * x5)
5           8   31.30177  0.155108  1.1496086 - (p(x0) + (x5 * x5))

best: x0*(-2.7326171) - x5*x5
Error in callback _flush_stdio (for post_execute), with arguments args (),kwargs {}:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 4095: unexpected end of data