# Zadanie 5: programowanie genetyczne i regresja symboliczna

Termin realizacji: 18 maja 2026

Zadanie do oddania przez MS Teams. Do oddania: kod oraz krótkie sprawozdanie w PDF (można na przykład przy użyciu `quarto render notebook.ipynb --to pdf`).

## Na 3.0

Do realizacji:

1. Zmodyfikuj przykład `pysr_demo.ipynb` tak, aby uczył się funkcji $f(x) = 2.2\sin(x_0 + 2 x_1) - x_5^2 - 3$ której dziedziną jest $\mathbb{R}^6$. Uczenie ma się odbywać w oparciu o 200 wylosowanych z dziedziny próbek (między -5 a 5).
2. Zanotuj wzory trzech rozwiązań o najwyższej wartości `score` oraz rozwiązanie `best` dla następujących zestawów ustawień:
   1. `binary_operators=["+", "*"], unary_operators=["cos", "exp", "sin"], maxsize=20`,
   2. `binary_operators=["+", "*", "-", "^"], unary_operators=["cos", "exp", "sin", "log"], maxsize=30`, (dodaj ograniczenie dla argumentów operatora "^": [https://astroautomata.com/PySR/v1.5.9/operators#custom](https://astroautomata.com/PySR/v1.5.9/operators#custom) ).
   3. `binary_operators=["+", "*", "-", "^"], unary_operators=["exp", "sin"], maxsize=15`.
3. Powtórz eksperymenty z zadania na 3.0 po dodaniu szumu do próbek z funkcji $f$ (rozkład normalny o średniej 0 i odchyleniu standardowym 0.5)

## Na 4.0

Do realizacji:

1. Punkty z zadania na 3.0.
2. Dodaj do porównania dopasowanie oparte o próbki losowane w szerszym zakresie (między -15 a 15) oraz wyższy poziom szumu (odchylenie standardowe równe 2 oraz 5).

## Na 5.0

Do realizacji:

1. Punkty z zadania na 4.0.
2. Zamień funkcję $f$ na $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$ gdzie $p(i)$ oznacza $i$-tą liczbę pierwszą. Uwzględnij `p` jako dodatkowy operator unarny analogicznie do przykładu "Julia packages and types" z notatnika `pysr_demo.ipynb`. Powtórz eksperymenty opisane w zadaniach na 3.0 i 4.0.

## Importy

In [134]:
import numpy as np
import sympy
from pysr import PySRRegressor

In [135]:
default_pysr_params = dict(
    populations=30,
    model_selection="best",
    niterations=40,
)

## Funkcja pomocnicza do wyświetlania wyników

In [136]:
def show_results(model):
    display(model.equations_.nlargest(3, 'score')[['complexity', 'loss', 'score', 'equation']])
    print('best:', model.sympy())

## 3.0 — Dane bez szumu, zakres [-5, 5]

Funkcja: $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - 3$, dziedzina $\mathbb{R}^6$, 200 próbek.

In [137]:
np.random.seed(0)
X = np.random.uniform(-5, 5, (200, 6))
y = 2.2 * np.sin(X[:, 0] + 2 * X[:, 1]) - X[:, 5]**2 - 3

### Konfiguracja 1 — `binary=["+","*"]`, `unary=["cos","exp","sin"]`, `maxsize=20`

In [138]:
model1 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1.fit(X, y)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.158
3           5.546e+01  1.239e-03  y = x₂ + -11.311
4           5.152e+01  7.370e-02  y = cos(x₅) + -10.987
5           6.759e+00  2.031e+00  y = (x₅ * -1.1932) * x₅
7           2.205e+00  5.600e-01  y = ((x₅ * -0.98155) * x₅) + -3.1631
9           2.197e+00  1.884e-03  y = (((x₅ * -0.9792) + -0.03255) * x₅) + -3.1777
11          2.132e+00  1.506e-02  y = ((x₅ * (x₅ + (x₄ * -0.034646))) + 3.2445) * -0.98022
12          2.091e+00  1.942e-02  y = (x₅ * (x₅ * -0.98271)) + (sin(-2.049 * x₁) + -3.1964)
13          2.054e+00  1.771e-02  y = ((sin(sin(x₁ + x₁)) + (x₅ * x₅)) + 3.2999) * -0.98022
14          6.559e-01  1.142e+00  y = ((x₅ * -0.9898) * x₅) + (sin(x₀ + (x₁ * 2.0044)) + -3....
                                      0895)
16          1.211e-06  6.601e+00  y = ((sin(x₀ + (x₁ * 2.0001)) + ((x₅ * x₅) * -0.45427)) * ...
                                      2.2013) + -2.9999
20          3.379e-10  2.046e+00  y = ((cos((x₁ + ((x₀ * 0.5) + 0.7854)) * 2) * -2.2) + (-1 ...
                                      * (x₅ * x₅))) + -3
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165911_CTyEOk/hall_of_fame.csv

In [139]:
show_results(model1)

,complexity,loss,score,equation
10,16,1.211017e-06,6.601147,((sin(x0 + (x1 * 2.000127)) + ((x5 * x5) * -0....
11,20,3.379090e-10,2.046049,((cos((x1 + ((x0 * 0.50000197) + 0.7854008)) *...
3,5,6.758767e+00,2.031154,(x5 * -1.1931679) * x5

best: -1.0000006*x5*x5 + cos((x0*0.50000197 + x1 + 0.7854008)*1.9999976)*(-2.2000005) - 2.9999948

### Konfiguracja 2 — `binary=["+","*","-","^"]`, `unary=["cos","exp","sin","log"]`, `maxsize=30`

Ograniczenie dla `^`: prawy argument ma maksymalną złożoność 1.

In [140]:
model2 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model2.fit(X, y)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.159
3           5.537e+01  2.049e-03  y = -11.021 - x₅
4           5.152e+01  7.208e-02  y = cos(x₅) - 10.987
5           2.224e+00  3.143e+00  y = -3.0128 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * -0.98154) * x₅) + -3.1631
9           2.194e+00  2.514e-03  y = ((x₀ * 0.05683) - (x₅ * x₅)) + -2.9963
10          2.134e+00  2.777e-02  y = ((sin(x₀) * -0.41059) + -3.0124) - (x₅ * x₅)
11          2.111e+00  1.104e-02  y = -3.795 - ((x₅ * x₅) - cos(cos(x₁ - 0.77582)))
13          1.784e+00  8.396e-02  y = -3.2998 - ((x₅ * x₅) - cos(x₀ * cos(x₁ - 0.75987)))
14          1.762e+00  1.242e-02  y = -3.1623 - ((x₅ * x₅) - sin(cos(cos(0.71765 - x₁) * x₀)...
                                      ))
15          1.734e+00  1.644e-02  y = -3.2375 - ((x₅ * x₅) - cos(cos(x₁ - 0.70119) * (x₀ * 0...
                                      .88161)))
16          1.468e+00  1.666e-01  y = 0.87014 - ((x₅ * x₅) - (cos(sin(cos(2.9541 - x₀) - x₁)...
                                      ) * -5.1565))
21          1.462e+00  7.667e-04  y = -3.5886 - ((x₅ * x₅) - cos(x₀ * (sin(cos(x₁ - (0.85103...
                                       - x₀))) * cos(x₁ - 0.75987))))
24          6.611e-01  2.645e-01  y = -3.1351 - ((x₅ * x₅) - (cos((((((0.068323 - x₁) * -1.0...
                                      029) + x₁) + 0.34967) + (x₀ - 1.062)) + -0.76829) - -0.127...
                                      95))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165913_WmhNly/hall_of_fame.csv

In [141]:
show_results(model2)

,complexity,loss,score,equation
3,5,2.224043,3.142667,-3.0128005 - (x5 * x5)
13,24,0.661125,0.264518,-3.1351306 - ((x5 * x5) - (cos((((((0.06832335...
11,16,1.467520,0.166617,0.8701383 - ((x5 * x5) - (cos(sin(cos(2.954069...

best: -(x5*x5 - (cos(x0 + x1 + (0.06832335 - x1)*(-1.0028973) - 1*1.0619982 - 0.7682885 + 0.34967357) - 1*(-0.12795098))) - 3.1351306

### Konfiguracja 3 — `binary=["+","*","-","^"]`, `unary=["exp","sin"]`, `maxsize=15`

In [142]:
model3 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model3.fit(X, y)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.560e+01  0.000e+00  y = -11.159
3           5.537e+01  2.049e-03  y = -11.021 - x₅
4           5.462e+01  1.364e-02  y = -11.159 - sin(x₀)
5           2.224e+00  3.201e+00  y = -3.0128 - (x₅ * x₅)
7           2.205e+00  4.262e-03  y = ((x₅ * x₅) - -3.2225) * -0.98155
9           2.153e+00  1.189e-02  y = (((x₄ * 0.03329) - x₅) * x₅) + -3.0191
10          2.106e+00  2.231e-02  y = (sin(x₁ * -2.0612) - (x₅ * x₅)) + -3.0706
11          2.067e+00  1.866e-02  y = (sin(sin(x₁ * -2.0553)) + -3.0645) - (x₅ * x₅)
12          2.050e+00  8.396e-03  y = sin(sin(sin(-2.0478 * x₁))) + (-3.0614 - (x₅ * x₅))
13          1.221e+00  5.181e-01  y = (sin(sin(x₀) + (x₁ * -2.0389)) - (x₅ * x₅)) + -2.9979
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165916_p6SEfF/hall_of_fame.csv

In [143]:
show_results(model3)

,complexity,loss,score,equation
3,5,2.224043,3.201109,-3.0128005 - (x5 * x5)
9,13,1.220844,0.518108,(sin(sin(x0) + (x1 * -2.0388968)) - (x5 * x5))...
6,10,2.105834,0.022311,(sin(x1 * -2.0612214) - (x5 * x5)) + -3.0706236

best: -x5*x5 + sin(x1*(-2.0388968) + sin(x0)) - 2.9978626

## 3.0 — Dane z szumem $\mathcal{N}(0,\,0.5^2)$, zakres [-5, 5]

In [144]:
np.random.seed(0)
X_n05 = np.random.uniform(-5, 5, (200, 6))
y_n05 = 2.2 * np.sin(X_n05[:, 0] + 2 * X_n05[:, 1]) - X_n05[:, 5]**2 - 3 + np.random.normal(0, 0.5, 200)

### Konfiguracja 1 (szum 0.5)

In [145]:
model1_n05 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1_n05.fit(X_n05, y_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.092
3           5.560e+01  5.008e-04  y = x₂ + -11.246
4           5.159e+01  7.493e-02  y = cos(x₅) + -10.922
5           6.855e+00  2.018e+00  y = x₅ * (x₅ * -1.188)
7           2.449e+00  5.148e-01  y = ((x₅ * x₅) * -0.97982) + -3.1117
9           2.434e+00  2.937e-03  y = (((x₅ + 0.04379) * x₅) * -0.97674) + -3.1309
11          2.363e+00  1.485e-02  y = (x₅ * ((-0.97839 * x₅) + (0.03612 * x₄))) + -3.1303
12          2.340e+00  9.922e-03  y = sin(x₁ * -2.0207) + ((x₅ * (x₅ * -0.98092)) + -3.169)
14          2.333e+00  1.370e-03  y = ((x₅ * ((x₅ + 0.040999) * -0.97272)) + (sin(x₀) * -0.4...
                                      3704)) + -3.1636
15          1.504e+00  4.390e-01  y = ((x₅ * x₅) * -0.97918) + (-3.1135 + (sin(x₁) * cos(x₁ ...
                                      + x₀)))
16          8.818e-01  5.340e-01  y = (((x₅ * -0.98883) * x₅) + -3.0354) + sin(x₀ + ((x₁ + 0...
                                      .014422) * 1.9844))
18          8.771e-01  2.671e-03  y = ((x₅ * ((x₅ + 0.03468) * -0.98884)) + sin(x₀ + ((x₁ * ...
                                      2.4032) * 0.82572))) + -3.0353
20          8.761e-01  5.954e-04  y = (((x₅ * (x₅ + 0.03468)) * -0.98884) + sin(x₀ + (((x₁ *...
                                       2.4032) + 0.03468) * 0.82572))) + -3.0353
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165918_rKmhNw/hall_of_fame.csv

In [146]:
show_results(model1_n05)

,complexity,loss,score,equation
3,5,6.855120,2.018258,x5 * (x5 * -1.1879785)
10,16,0.881831,0.533970,(((x5 * -0.98883396) * x5) + -3.035409) + sin(...
4,7,2.448527,0.514755,((x5 * x5) * -0.97982454) + -3.1116517

best: x5*(-0.98883396)*x5 + sin(x0 + (x1 + 0.014421785)*1.9843959) - 3.035409

### Konfiguracja 2 (szum 0.5)

In [147]:
model2_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model2_n05.fit(X_n05, y_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.092
3           5.528e+01  3.373e-03  y = -10.955 - x₅
4           5.159e+01  6.919e-02  y = cos(x₅) + -10.922
5           2.471e+00  3.039e+00  y = -2.9473 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = ((x₅ * -0.97982) * x₅) + -3.1117
9           2.434e+00  2.937e-03  y = ((x₅ * (x₅ + 0.043798)) + 3.2054) * -0.97674
10          2.378e+00  2.315e-02  y = (-2.9469 - (x₅ * x₅)) - (sin(x₀) * 0.41637)
12          2.346e+00  6.942e-03  y = (-3.225 - ((sin(x₀) * 0.45194) + (x₅ * x₅))) * 0.97554
13          1.978e+00  1.707e-01  y = (sin((cos(x₁) * -2.7834) - x₀) + -2.8893) - (x₅ * x₅)
17          1.963e+00  1.799e-03  y = (sin((cos(x₁) * -2.77) + (x₀ * -1.0481)) + (-3.4844 - ...
                                      (x₅ * x₅))) - -0.58498
18          1.423e+00  3.221e-01  y = (1.2843 - (x₅ * x₅)) - exp(1.4356 - (cos(x₀) * (sin(x₁...
                                      ) * sin(cos(x₁)))))
20          1.418e+00  1.600e-03  y = (1.3816 - (x₅ * x₅)) - exp(1.4631 - ((sin(x₁) * sin(1....
                                      5628 - x₀)) * sin(cos(x₁))))
25          1.407e+00  1.533e-03  y = (-0.021849 - (x₅ * x₅)) + (0.3257 - (exp(1.3791 - (sin...
                                      (x₁) * (sin(1.5833 - x₀) * cos(x₁)))) - cos(sin(x₀))))
27          1.393e+00  5.005e-03  y = (((0.98056 - (x₅ * x₅)) - exp(1.4151 - ((sin(x₁) * sin...
                                      (1.5608 - x₀)) * cos(x₁)))) + 0.98197) - cos(sin(x₁ * 1.41...
                                      59))
29          1.356e+00  1.354e-02  y = ((0.9981 - (x₅ * x₅)) - exp(1.4301 - (cos(x₁) * (sin(x...
                                      ₁) * sin(1.5489 - x₀))))) + (0.99934 - cos(sin((x₀ * -0.56...
                                      52) - -0.48102)))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165919_d9WSH4/hall_of_fame.csv

In [148]:
show_results(model2_n05)

,complexity,loss,score,equation
3,5,2.471086,3.038596,-2.947266 - (x5 * x5)
10,18,1.422674,0.322105,(1.2842985 - (x5 * x5)) - exp(1.4356381 - (cos...
8,13,1.977515,0.170739,(sin((cos(x1) * -2.7834344) - x0) + -2.8892562...

best: -x5*x5 - exp(1.4356381 - sin(x1)*sin(cos(x1))*cos(x0)) + 1.2842985

### Konfiguracja 3 (szum 0.5)

In [149]:
model3_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model3_n05.fit(X_n05, y_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.566e+01  0.000e+00  y = -11.094
3           5.528e+01  3.373e-03  y = -10.955 - x₅
4           5.467e+01  1.109e-02  y = -11.092 - sin(x₀)
5           2.471e+00  3.097e+00  y = -2.9473 - (x₅ * x₅)
7           2.449e+00  4.585e-03  y = ((x₅ * -0.97983) * x₅) - 3.1116
9           2.420e+00  5.887e-03  y = -3.1303 - ((x₅ - (x₄ * 0.037461)) * x₅)
10          2.360e+00  2.515e-02  y = -3.0128 + (sin(x₁ * -2.025) - (x₅ * x₅))
11          2.318e+00  1.792e-02  y = (sin(sin(-2.025 * x₁)) + -3.0128) - (x₅ * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165922_7V26vx/hall_of_fame.csv

In [150]:
show_results(model3_n05)

,complexity,loss,score,equation
3,5,2.471086,3.096697,-2.9473233 - (x5 * x5)
6,10,2.359764,0.025150,-3.012764 + (sin(x1 * -2.0250006) - (x5 * x5))
7,11,2.317862,0.017916,(sin(sin(-2.0250006 * x1)) + -3.012764) - (x5 ...

best: -x5*x5 - 2.9473233

## 4.0 — Zakres [-15, 15], szum $\sigma=2$

In [151]:
np.random.seed(0)
X_w2 = np.random.uniform(-15, 15, (200, 6))
y_w2 = 2.2 * np.sin(X_w2[:, 0] + 2 * X_w2[:, 1]) - X_w2[:, 5]**2 - 3 + np.random.normal(0, 2, 200)

### Konfiguracja 1 (zakres [-15,15], σ=2)

In [152]:
model1_w2 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1_w2.fit(X_w2, y_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.478
5           9.261e+00  3.074e+00  y = x₅ * (x₅ * -1.0195)
7           5.635e+00  2.484e-01  y = (x₅ * (x₅ * -0.99853)) + -2.8225
9           5.631e+00  3.749e-04  y = (((x₅ * -0.99872) + 0.0077422) * x₅) + -2.8117
11          5.541e+00  8.078e-03  y = (((x₅ * x₅) + sin(exp(x₄))) + 2.7308) * -0.99876
12          5.147e+00  7.359e-02  y = (sin(x₀ * 1.4498) + ((x₅ * -0.9984) * x₅)) + -2.8635
14          5.145e+00  2.784e-04  y = (sin(x₀ * 1.4495) + (((x₅ * -0.99855) + 0.0063822) * x...
                                      ₅)) + -2.8549
17          5.035e+00  7.178e-03  y = ((sin(x₀ * 1.4452) + (sin(x₅) * -0.46791)) + -2.9198) ...
                                      + (x₅ * (x₅ * -0.99799))
19          5.023e+00  1.190e-03  y = ((((x₅ + -0.013204) * -0.99828) * x₅) + -2.905) + ((si...
                                      n(x₅) * -0.49264) + sin(x₀ * 1.4443))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165923_9qe6bI/hall_of_fame.csv

In [153]:
show_results(model1_w2)

,complexity,loss,score,equation
2,5,9.260938,3.074411,x5 * (x5 * -1.0195214)
3,7,5.635047,0.248400,(x5 * (x5 * -0.9985284)) + -2.8225174
6,12,5.147494,0.073588,(sin(x0 * 1.4498211) + ((x5 * -0.9983998) * x5...

best: x5*x5*(-0.9985284) - 2.8225174

### Konfiguracja 2 (zakres [-15,15], σ=2)

In [154]:
model2_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model2_w2.fit(X_w2, y_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.026
3           4.336e+03  1.630e-02  y = x₂ + -76.483
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.622e-04  y = -2.8226 - ((x₅ * 0.99853) * x₅)
9           5.586e+00  4.350e-03  y = ((x₄ * 0.030493) - (x₅ * x₅)) - 2.7199
10          5.042e+00  1.024e-01  y = (sin(0.11002 ^ x₄) + -2.7035) - (x₅ * x₅)
12          5.004e+00  3.845e-03  y = (sin((0.11002 ^ x₄) + 0.36904) - (x₅ * x₅)) - 2.8455
13          4.966e+00  7.542e-03  y = (sin((0.11002 ^ x₄) - exp(x₄)) - 2.6391) - (x₅ * x₅)
14          4.927e+00  7.932e-03  y = (sin((0.11002 ^ x₄) - sin(exp(x₄))) - 2.6391) - (x₅ * ...
                                      x₅)
17          4.866e+00  4.147e-03  y = (sin(((0.11002 ^ x₄) - exp(x₄)) - sin(exp(x₄))) - 2.63...
                                      91) - (x₅ * x₅)
18          4.840e+00  5.390e-03  y = (sin(0.11002 ^ x₄) - (x₅ * x₅)) - (2.6391 + sin(exp(x₄...
                                      ) - (0.11002 ^ x₄)))
19          4.803e+00  7.626e-03  y = ((sin(0.11002 ^ x₄) + sin(sin(exp(-0.72049 * x₀)) * x₅...
                                      )) - (x₅ * x₅)) - 2.6391
20          4.799e+00  9.271e-04  y = sin(0.11002 ^ x₄) + ((sin(sin(sin(exp(-0.72049 * x₀)) ...
                                      * x₅)) - (x₅ * x₅)) - 2.6391)
23          4.662e+00  9.598e-03  y = ((sin(0.11002 ^ x₄) + sin(sin(x₅ * exp(x₀ * -0.72049))...
                                       * (x₅ - -1.0129))) - (x₅ * x₅)) - 2.6391
25          4.629e+00  3.602e-03  y = ((sin(0.11002 ^ x₄) + sin((x₅ - -1.0129) * sin((x₅ * e...
                                      xp(x₀ * -0.72049)) - 0.014981))) - (x₅ * x₅)) - 2.6391
29          4.627e+00  7.897e-05  y = ((sin(0.11002 ^ x₄) - (x₅ * x₅)) - 2.6391) + sin((0.11...
                                      002 ^ x₄) + (sin(x₅ - -0.72049) * (sin((x₅ * -0.72049) * x...
                                      ₅) - 0.14304)))
30          4.561e+00  1.450e-02  y = ((sin(0.11002 ^ x₄) - (x₅ * x₅)) - 2.6391) + sin((0.11...
                                      002 ^ x₄) + (sin(x₅ - cos(x₀)) * (sin((x₅ * -0.72049) * x₅...
                                      ) - 0.14304)))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165925_E5iAko/hall_of_fame.csv

In [155]:
show_results(model2_w2)

,complexity,loss,score,equation
2,5,5.644776,3.321948,-2.7146325 - (x5 * x5)
5,10,5.042408,0.102421,(sin(0.11002277 ^ x4) + -2.7034533) - (x5 * x5)
1,3,4335.649400,0.016550,x2 + -76.48342

best: -x5*x5 - 2.7146325

### Konfiguracja 3 (zakres [-15,15], σ=2)

In [156]:
model3_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model3_w2.fit(X_w2, y_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.482e+03  0.000e+00  y = -76.023
3           4.336e+03  1.630e-02  y = x₂ + -76.487
5           5.645e+00  3.322e+00  y = -2.7146 - (x₅ * x₅)
7           5.635e+00  8.621e-04  y = (x₅ * (x₅ * -0.99853)) - 2.8226
9           5.554e+00  7.286e-03  y = (-2.7147 - (x₅ * x₅)) - sin(exp(x₄))
10          5.159e+00  7.370e-02  y = sin(x₀ * 1.4504) - ((x₅ * x₅) + 2.7462)
12          5.142e+00  1.668e-03  y = sin((x₀ + 2.2929) * -1.4556) - ((x₅ * x₅) + 2.7374)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165928_PDGlUY/hall_of_fame.csv

In [157]:
show_results(model3_w2)

,complexity,loss,score,equation
2,5,5.644776,3.321948,-2.7146327 - (x5 * x5)
5,10,5.158974,0.073696,sin(x0 * 1.4504354) - ((x5 * x5) + 2.7461896)
1,3,4335.649000,0.016550,x2 + -76.4867

best: -x5*x5 - 2.7146327

## 4.0 — Zakres [-15, 15], szum $\sigma=5$

In [158]:
np.random.seed(0)
X_w5 = np.random.uniform(-15, 15, (200, 6))
y_w5 = 2.2 * np.sin(X_w5[:, 0] + 2 * X_w5[:, 1]) - X_w5[:, 5]**2 - 3 + np.random.normal(0, 5, 200)

### Konfiguracja 1 (zakres [-15,15], σ=5)

In [159]:
model1_w5 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin"],
    maxsize=20,
    **default_pysr_params,
)
model1_w5.fit(X_w5, y_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.634
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.662e+01  2.547e+00  y = x₅ * (x₅ * -1.0161)
7           2.375e+01  5.716e-02  y = ((x₅ * -0.99738) * x₅) + -2.5136
9           2.374e+01  2.401e-04  y = (((x₅ * -0.99708) + -0.012737) * x₅) + -2.5308
10          2.371e+01  1.187e-03  y = (((x₅ * -0.9975) * x₅) + -2.5511) + sin(x₃)
11          2.328e+01  1.830e-02  y = ((exp(sin(x₅)) + (x₅ * x₅)) * -0.9975) + -1.2036
12          2.252e+01  3.290e-02  y = sin(x₀ * 1.4636) + (((x₅ * -0.99731) * x₅) + -2.5538)
14          2.251e+01  3.303e-04  y = sin(x₀ * 1.4641) + ((x₅ * ((x₅ * -0.99696) + -0.01455)...
                                      ) + -2.5733)
17          2.239e+01  1.797e-03  y = ((cos(x₁ + 2.257) + sin(x₅ * 1.6465)) + ((x₅ * -0.9957...
                                      2) * x₅)) + -2.5984
18          2.224e+01  6.777e-03  y = ((cos(exp(x₄) + 2.3308) + -2.0123) + (-0.99662 * (x₅ *...
                                       x₅))) + cos(x₁ * -0.68785)
19          2.217e+01  3.193e-03  y = ((x₅ * -0.99572) * x₅) + (cos(x₁ + 2.257) + (cos(x₁ * ...
                                      (x₃ * -0.68646)) + -2.5984))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165930_U9OgsQ/hall_of_fame.csv

In [160]:
show_results(model1_w5)

,complexity,loss,score,equation
2,5,26.622316,2.547511,x5 * (x5 * -1.0160631)
3,7,23.746544,0.057156,((x5 * -0.9973819) * x5) + -2.513649
7,12,22.523650,0.032898,sin(x0 * 1.4636142) + (((x5 * -0.9973096) * x5...

best: x5*x5*(-1.0160631)

### Konfiguracja 2 (zakres [-15,15], σ=5)

In [161]:
model2_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model2_w5.fit(X_w5, y_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.633
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.378e+01  2.604e+00  y = -2.3219 - (x₅ * x₅)
7           2.375e+01  6.468e-04  y = (-2.5203 - (x₅ * x₅)) * 0.99738
8           2.335e+01  1.673e-02  y = (-2.3232 - (x₅ * x₅)) - sin(x₁)
9           2.335e+01  2.944e-04  y = (-2.323 - (x₅ * x₅)) - sin(sin(x₁))
10          2.307e+01  1.182e-02  y = -2.3251 - (sin(x₁ - x₅) + (x₅ * x₅))
11          2.279e+01  1.225e-02  y = (-2.2955 - (x₅ * x₅)) - sin(x₁ - cos(x₅))
12          2.257e+01  9.758e-03  y = (-0.41114 - ((x₅ * x₅) - sin(x₀ * 1.4725))) - 2.0372
13          2.210e+01  2.085e-02  y = -2.2848 - ((x₅ * x₅) - sin((x₅ + exp(x₀)) - x₁))
16          2.209e+01  2.276e-04  y = ((sin(27.698 * exp(x₀)) - (x₅ * x₅)) - sin(x₄ - x₀)) -...
                                       2.4582
18          2.178e+01  7.059e-03  y = (-0.21376 - (x₅ * x₅)) - ((sin((x₁ - exp(x₀)) - x₅) + ...
                                      sin(x₁)) + 2.0403)
19          2.173e+01  2.137e-03  y = (sin(-0.21376) - (x₅ * x₅)) - ((sin(x₅) + 2.0403) + si...
                                      n((x₁ - exp(x₀)) - x₅))
20          2.160e+01  6.306e-03  y = (sin(x₂ * 0.58015) - (x₅ * x₅)) - (sin(((x₁ - exp(x₀))...
                                       - x₅) + -0.32737) + 2.3336)
21          2.141e+01  8.835e-03  y = (sin(0.59341 * x₂) - (x₅ * x₅)) - (sin((x₁ - exp(x₀)) ...
                                      - x₅) + (sin(x₁) + 2.0403))
23          2.127e+01  3.258e-03  y = (((-0.85459 * sin(x₅)) - (x₅ * x₅)) - (sin(x₁) - sin(x...
                                      ₅ + (exp(x₀) - x₁)))) - (2.7588 - 0.37661)
24          2.112e+01  7.026e-03  y = ((cos(x₅ * 2.1047) - (x₅ * x₅)) - (sin(exp(x₁ + 49.911...
                                      )) - sin(x₅ + (exp(x₀) - x₁)))) - 2.2119
25          2.054e+01  2.777e-02  y = ((sin(x₅ * -0.9203) - (x₅ * x₅)) - exp(sin(sin(x₄) + 1...
                                      .8689) - sin((x₅ + exp(x₀)) - x₁))) - -0.40705
29          1.999e+01  6.734e-03  y = (sin(sin(0.27806 - x₅)) - (x₅ * x₅)) - (exp(sin(exp(si...
                                      n((0.32142 - x₁) * 11.586))) - sin(exp(x₀) + (x₅ - x₁))) -...
                                       0.26763)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165931_lBGC6Z/hall_of_fame.csv

In [162]:
show_results(model2_w5)

,complexity,loss,score,equation
2,5,23.777332,2.604020,-2.3218646 - (x5 * x5)
17,25,20.539080,0.027774,((sin(x5 * -0.92030466) - (x5 * x5)) - exp(sin...
9,13,22.103582,0.020849,-2.2847507 - ((x5 * x5) - sin((x5 + exp(x0)) -...

best: -x5*x5 - 2.3218646

### Konfiguracja 3 (zakres [-15,15], σ=5)

In [163]:
model3_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    **default_pysr_params,
)
model3_w5.fit(X_w5, y_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.489e+03  0.000e+00  y = -75.633
3           4.345e+03  1.610e-02  y = x₂ + -76.091
5           2.378e+01  2.604e+00  y = -2.3211 - (x₅ * x₅)
7           2.375e+01  6.468e-04  y = (-2.5198 - (x₅ * x₅)) * 0.99739
8           2.335e+01  1.673e-02  y = -2.3232 - (sin(x₁) + (x₅ * x₅))
9           2.335e+01  2.944e-04  y = -2.323 - ((x₅ * x₅) + sin(sin(x₁)))
10          2.256e+01  3.440e-02  y = sin(x₀ * 1.4643) + (-2.3568 - (x₅ * x₅))
11          2.247e+01  3.735e-03  y = -2.3712 - (sin(exp(x₅) * -7.387) + (x₅ * x₅))
12          2.230e+01  7.781e-03  y = (-2.3826 - (x₅ * x₅)) + (sin(x₀ * 1.467) * 1.7193)
13          2.230e+01  4.691e-05  y = (sin((x₀ * 1.4713) + exp(x₀)) + -2.3583) - (x₅ * x₅)
14          2.222e+01  3.401e-03  y = ((sin((x₀ * 1.4713) + 0.23013) * 1.7537) + -2.3583) - ...
                                      (x₅ * x₅)
15          2.184e+01  1.751e-02  y = ((sin((x₀ * 1.4713) + exp(x₀)) * 1.7537) + -2.3583) - ...
                                      (x₅ * x₅)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin']"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,None
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165934_t0B5PD/hall_of_fame.csv

In [164]:
show_results(model3_w5)

,complexity,loss,score,equation
2,5,23.777332,2.604020,-2.3210776 - (x5 * x5)
6,10,22.556126,0.034407,sin(x0 * 1.46426) + (-2.3567696 - (x5 * x5))
11,15,21.835169,0.017513,((sin((x0 * 1.4712893) + exp(x0)) * 1.7536877)...

best: -x5*x5 - 2.3210776

## 5.0 — Operator liczb pierwszych $p(i)$

Funkcja: $f(x) = 2.2\sin(x_0 + 2x_1) - x_5^2 - p(\lfloor x_0 \rfloor)$

### Instalacja Primes.jl i definicja operatora `p`

In [165]:
from pysr import jl

jl.seval("""
import Pkg
Pkg.add(\"Primes\")
""")

   Resolving package versions...
     Project No packages added to or removed from `/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/julia_env/Project.toml`
    Manifest No packages added to or removed from `/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/julia_env/Manifest.toml`

In [166]:
jl.seval("using Primes: prime")

In [167]:
jl.seval("""
function p(i::T) where T
    if 0.5 < i < 1000
        return T(prime(round(Int, i)))
    else
        return T(NaN)
    end
end
""")

p (generic function with 1 method)

Definicja `sympy_p` oraz pomocnicza funkcja Pythonowa do generowania próbek.

In [168]:
class sympy_p(sympy.Function):
    pass

def p_python(x0_val):
    i = int(np.floor(x0_val))
    if 1 <= i <= 999:
        return float(sympy.prime(i))
    return np.nan

In [169]:
def make_data_prime(low, high, n=200, noise_std=0.0, seed=0):
    rng = np.random.default_rng(seed)
    # generujemy więcej próbek, bo część x0 daje NaN
    X_raw = rng.uniform(low, high, (n * 6, 6))
    p_vals = np.array([p_python(x) for x in X_raw[:, 0]])
    y_raw = 2.2 * np.sin(X_raw[:, 0] + 2 * X_raw[:, 1]) - X_raw[:, 5]**2 - p_vals
    if noise_std > 0:
        y_raw += rng.normal(0, noise_std, len(y_raw))
    mask = ~np.isnan(y_raw)
    return X_raw[mask][:n], y_raw[mask][:n]

### 5.0 — Bez szumu, zakres [-5, 5]

In [170]:
X_p, y_p = make_data_prime(-5, 5)
print(f'Próbek: {len(y_p)}')

Próbek: 200

### Konfiguracja 1 z operatorem `p` (bez szumu)

In [171]:
model1_p = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p.fit(X_p, y_p)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:
[ Info: Results saved to:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
4           5.058e+01  2.706e-02  y = cos(x₅) + -11.678
5           1.433e+01  1.261e+00  y = x₅ * (x₅ * -1.2969)
7           3.456e+00  7.112e-01  y = (x₀ + (x₅ * x₅)) * -1.0778
9           2.617e+00  1.391e-01  y = ((x₀ * 1.4961) + (x₅ * x₅)) * -0.97779
11          2.610e+00  1.442e-03  y = (x₀ * -1.5292) + (((x₅ * x₅) + -0.2662) * -0.98175)
12          2.520e+00  3.512e-02  y = (((x₀ + (x₅ * x₅)) * -0.97783) + -1.4695) + sin(x₀)
14          2.443e+00  1.547e-02  y = ((x₅ * (x₅ * -0.97859)) + (sin(x₀ + -0.15294) * 2.4376...
                                      )) + -4.647
16          2.272e+00  3.621e-02  y = (sin(x₀) * cos(sin(x₁))) + ((((x₅ * x₅) + x₀) * -0.985...
                                      91) + -1.3795)
18          2.069e+00  4.691e-02  y = ((cos(sin(x₁) * -1.8944) * sin(x₀)) + ((x₀ + (x₅ * x₅)...
                                      ) * -1.0018)) + -1.2017
───────────────────────────────────────────────────────────────────────────────────────────────────

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165937_gDwdz9/hall_of_fame.csv

In [172]:
show_results(model1_p)

,complexity,loss,score,equation
2,5,14.333841,1.260923,x5 * (x5 * -1.2968999)
3,7,3.456479,0.711186,(x0 + (x5 * x5)) * -1.0778418
4,9,2.617216,0.139070,((x0 * 1.4960623) + (x5 * x5)) * -0.9777871

best: (x0*1.4960623 + x5*x5)*(-0.9777871)

### Konfiguracja 2 z operatorem `p` (bez szumu)

In [173]:
model2_p = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model2_p.fit(X_p, y_p)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8112 - x₀
4           5.058e+01  1.828e-02  y = cos(x₅) + -11.678
5           5.660e+00  2.190e+00  y = -4.2634 - (x₅ * x₅)
7           2.645e+00  3.804e-01  y = (x₀ * -1.4136) - (x₅ * x₅)
9           2.626e+00  3.475e-03  y = (0.38595 - (x₅ * x₅)) + (x₀ * -1.5246)
10          2.492e+00  5.252e-02  y = ((sin(x₀) * 2.3591) + -4.3096) - (x₅ * x₅)
12          2.466e+00  5.299e-03  y = (-4.4779 - (x₅ * x₅)) + (sin(x₀ + -0.14824) * 2.4249)
14          2.309e+00  3.274e-02  y = (sin(x₀ - cos(cos(x₁))) + (-1.5453 - x₀)) - (x₅ * x₅)
15          2.219e+00  3.999e-02  y = cos(x₁ - cos(x₁ + x₀)) + ((x₀ * -1.4263) - (x₅ * x₅))
16          4.479e-01  1.600e+00  y = (x₀ * -1.4397) - ((sin((x₁ + x₀) + x₁) * -2.6289) + (x...
                                      ₅ * x₅))
17          3.604e-01  2.172e-01  y = (x₀ * -1.4397) - ((sin(sin(x₁ + (x₀ + x₁))) * -2.6289)...
                                       + (x₅ * x₅))
18          3.379e-01  6.462e-02  y = (x₀ * -1.4397) - ((sin((x₀ + x₁) + (x₁ - 0.037464)) * ...
                                      -2.1661) + (x₅ * x₅))
20          3.017e-01  5.660e-02  y = ((x₀ * -1.584) + 0.50355) - ((x₅ * x₅) + (cos(x₁ + (x₀...
                                       + (x₁ - -1.5855))) * 2.1592))
29          1.980e-01  4.678e-02  y = ((x₀ * -1.0246) - ((cos(-4.7267 - ((x₁ + x₁) + x₀)) * ...
                                      -2.138) + ((x₅ * x₅) - -1.3955))) + cos(((x₀ - x₁) + -1.95...
                                      34) + x₁)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165939_kfClk2/hall_of_fame.csv

In [174]:
show_results(model2_p)

,complexity,loss,score,equation
3,5,5.659596,2.190194,-4.2633934 - (x5 * x5)
10,16,0.447864,1.600256,(x0 * -1.4396514) - ((sin((x1 + x0) + x1) * -2...
4,7,2.644633,0.380410,(x0 * -1.4136072) - (x5 * x5)

best: x0*(-1.0246235) - (x5*x5 + cos(-(x0 + x1 + x1) - 4.726683)*(-2.1380002) - 1*(-1.3954569)) + cos(x0 - x1 + x1 - 1.953367)

### Konfiguracja 3 z operatorem `p` (bez szumu)

In [175]:
model3_p = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model3_p.fit(X_p, y_p)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.486e+01  0.000e+00  y = -11.86
3           5.151e+01  3.144e-02  y = -8.8112 - x₀
5           5.660e+00  1.104e+00  y = -4.263 - (x₅ * x₅)
7           2.985e+00  3.198e-01  y = -1.2137 - ((x₅ * x₅) + x₀)
9           2.581e+00  7.271e-02  y = (-0.25775 - (x₅ * x₅)) - (x₀ ^ 1.2265)
10          2.423e+00  6.340e-02  y = (0.063861 - (x₅ * x₅)) - p(x₀ + -0.50052)
12          2.375e+00  1.006e-02  y = (sin(x₁ * -1.9894) - (x₅ * x₅)) - (x₀ * 1.4266)
13          2.363e+00  4.946e-03  y = (sin(sin(x₁ * -1.9894)) - (x₅ * x₅)) - (x₀ * 1.4266)
14          2.355e+00  3.445e-03  y = ((-0.6581 * sin(x₁ + x₁)) - (x₅ * x₅)) - (x₀ * 1.4266)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165942_pUIOd5/hall_of_fame.csv

In [176]:
show_results(model3_p)

   complexity      loss     score                                     equation
2           5  5.659594  1.104241                       -4.2630405 - (x5 * x5)
3           7  2.985402  0.319809                -1.2136977 - ((x5 * x5) + x0)
4           9  2.581341  0.072713  (-0.2577459 - (x5 * x5)) - (x0 ^ 1.2264752)

best: -(x0 + x5*x5) - 1.2136977

### 5.0 — Szum $\sigma=0.5$, zakres [-5, 5]

In [177]:
X_p_n05, y_p_n05 = make_data_prime(-5, 5, noise_std=0.5)

### Konfiguracja 1 z operatorem `p` (szum 0.5)

In [178]:
model1_p_n05 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p_n05.fit(X_p_n05, y_p_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.902
4           5.090e+01  2.654e-02  y = cos(x₅) + -11.721
5           1.463e+01  1.247e+00  y = x₅ * (x₅ * -1.3003)
7           4.817e+00  5.553e-01  y = ((x₅ * x₅) + x₀) * -0.99929
9           2.893e+00  2.550e-01  y = ((x₅ * -0.98097) * x₅) + (x₀ * -1.4639)
11          2.891e+00  3.512e-04  y = ((x₀ * -1.4983) + 0.13562) + ((x₅ * -0.98301) * x₅)
12          2.776e+00  4.037e-02  y = ((sin(x₀) + ((x₅ * x₅) * -0.42395)) + -1.9429) * 2.313...
                                      6
14          2.765e+00  2.035e-03  y = ((sin(x₀ + -0.10004) + ((x₅ * x₅) * -0.41695)) + -1.96...
                                      08) * 2.3511
16          2.700e+00  1.195e-02  y = ((sin(x₀) * 2.3091) + ((x₅ * (x₅ * -0.98145)) + -4.479...
                                      8)) + (x₄ * 0.096427)
17          1.816e+00  3.968e-01  y = (((x₅ * -0.33956) * x₅) + (sin(sin(x₁ * 1.8946) + x₀) ...
                                      + -1.6127)) * 2.8692
18          1.728e+00  4.966e-02  y = (((x₅ * (x₅ * -0.33842)) + sin(sin(sin(x₁ * 1.8947)) +...
                                       x₀)) + -1.6106) * 2.8771
19          5.097e-01  1.221e+00  y = (sin(x₀) + (((x₅ * (x₅ * -0.44332)) + sin((x₀ + x₁) + ...
                                      x₁)) + -1.9334)) * 2.2664
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165944_a2DNiZ/hall_of_fame.csv

In [179]:
show_results(model1_p_n05)

,complexity,loss,score,equation
2,5,14.626331,1.247088,x5 * (x5 * -1.300306)
11,19,0.509689,1.220743,(sin(x0) + (((x5 * (x5 * -0.4433225)) + sin((x...
3,7,4.817347,0.555300,((x5 * x5) + x0) * -0.9992909

best: (x5*x5*(-0.4433225) + sin(x0) + sin(x0 + x1 + x1) - 1.9334198)*2.2664104

### Konfiguracja 2 z operatorem `p` (szum 0.5)

In [180]:
model2_p_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model2_p_n05.fit(X_p_n05, y_p_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.901
3           5.186e+01  3.052e-02  y = -8.8502 - x₀
4           5.090e+01  1.859e-02  y = cos(x₅) + -11.719
5           5.818e+00  2.169e+00  y = -4.3039 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.904e-03  y = (-0.3641 - (x₅ * x₅)) - (x₀ ^ 1.213)
10          2.725e+00  5.302e-02  y = (0.035324 - (x₅ * x₅)) - p(x₀ - 0.49052)
12          2.665e+00  1.106e-02  y = ((x₄ * 0.091441) - (x₅ * x₅)) - p(x₀ - 0.49052)
13          2.616e+00  1.874e-02  y = (((sin(x₁) * 0.091441) - x₅) * x₅) - p(x₀ - 0.49052)
14          1.249e+00  7.389e-01  y = (sin((x₁ + x₀) + x₁) - (x₀ ^ 1.2689)) - (x₅ * x₅)
16          1.208e+00  1.686e-02  y = (sin((x₀ + x₁) + x₁) - ((x₀ ^ 1.2207) + 0.35756)) - (x...
                                      ₅ * x₅)
18          1.207e+00  3.756e-04  y = ((0.010984 - x₅) * x₅) - (((x₀ ^ 1.2206) - sin(x₁ + (x...
                                      ₀ + x₁))) - -0.35765)
20          9.411e-01  1.244e-01  y = ((-0.35894 - (x₅ * x₅)) - (x₀ ^ 1.2206)) - (sin((0.015...
                                      948 - (x₁ + x₁)) - x₀) * 1.2575)
21          5.827e-01  4.794e-01  y = (sin((x₁ + x₀) + x₁) - (x₅ * x₅)) - ((x₀ ^ 1.2751) - s...
                                      in((x₁ + x₀) + x₁))
22          5.357e-01  8.420e-02  y = ((-0.35894 - (x₅ * x₅)) - (x₀ ^ 1.2206)) - (sin((0.015...
                                      948 - (x₁ + x₁)) - x₀) * (1.2575 - -0.97342))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165945_xpK3SB/hall_of_fame.csv

In [181]:
show_results(model2_p_n05)

,complexity,loss,score,equation
3,5,5.818120,2.168934,-4.303866 - (x5 * x5)
9,14,1.249330,0.738906,(sin((x1 + x0) + x1) - (x0 ^ 1.2688816)) - (x5...
13,21,0.582714,0.479376,(sin((x1 + x0) + x1) - (x5 * x5)) - ((x0 ^ 1.2...

best: -x5*x5 - (x0**1.2750595 - sin(x0 + x1 + x1)) + sin(x0 + x1 + x1)

### Konfiguracja 3 z operatorem `p` (szum 0.5)

In [182]:
model3_p_n05 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model3_p_n05.fit(X_p_n05, y_p_n05)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           5.512e+01  0.000e+00  y = -11.901
3           5.186e+01  3.052e-02  y = -8.8532 - x₀
5           5.818e+00  1.094e+00  y = -4.3039 - (x₅ * x₅)
7           2.913e+00  3.459e-01  y = (x₀ * -1.4217) - (x₅ * x₅)
9           2.873e+00  6.904e-03  y = (-0.36473 - (x₅ * x₅)) - (x₀ ^ 1.2129)
10          2.718e+00  5.552e-02  y = ((x₅ * x₅) + p(x₀ + -0.49789)) * -0.9908
12          2.698e+00  3.627e-03  y = -0.26438 - ((p(x₀ + -0.49564) + (x₅ * x₅)) * 0.97566)
14          2.698e+00  1.269e-04  y = -0.26334 - ((p(x₀ + -0.49212) + (x₅ * (x₅ + 0.0099391)...
                                      )) * 0.97568)
15          2.611e+00  3.273e-02  y = -0.096375 - ((x₅ * x₅) + (p(x₀ + -0.49212) - (exp(x₄) ...
                                      * 0.0099391)))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165948_BdxWd1/hall_of_fame.csv

In [183]:
show_results(model3_p_n05)

   complexity      loss     score                                     equation
2           5  5.818119  1.093766                       -4.3039336 - (x5 * x5)
3           7  2.913032  0.345891                (x0 * -1.4216933) - (x5 * x5)
5          10  2.717906  0.055525  ((x5 * x5) + p(x0 + -0.49789006)) * -0.9908

best: x0*(-1.4216933) - x5*x5

### 5.0 — Zakres [-15, 15], szum $\sigma=2$

In [184]:
X_p_w2, y_p_w2 = make_data_prime(-15, 15, noise_std=2)

### Konfiguracja 1 z operatorem `p` (zakres [-15,15], σ=2)

In [185]:
model1_p_w2 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p_w2.fit(X_p_w2, y_p_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.209
3           4.632e+03  1.532e-04  y = x₂ + -95.437
4           4.624e+03  1.210e-03  y = sin(x₂) + -95.208
5           3.854e+02  2.485e+00  y = (x₅ * x₅) * -1.1555
7           1.546e+02  4.566e-01  y = -1.0965 * ((x₅ * x₅) + x₀)
8           9.320e+00  2.809e+00  y = (p(x₀) + (x₅ * x₅)) * -0.989
10          6.516e+00  1.789e-01  y = (p(x₀ * 0.95491) + (x₅ * x₅)) * -0.99927
12          6.507e+00  7.212e-04  y = (((x₅ * x₅) + p(x₀ * 0.9549)) * -1.0003) + 0.13221
14          6.463e+00  3.428e-03  y = ((p(x₀ + -0.5075) + (x₅ * x₅)) + cos(cos(x₂))) * -0.99...
                                      592
15          6.379e+00  1.301e-02  y = ((p(0.95469 * x₀) + (x₅ * x₅)) * -0.99925) + cos(x₂ * ...
                                      x₀)
16          6.357e+00  3.412e-03  y = ((x₅ * x₅) + (sin(sin(x₄ * x₄)) + p(x₀ * 0.95491))) * ...
                                      -0.99927
17          6.341e+00  2.484e-03  y = ((x₅ * x₅) + (sin(sin(sin(x₄ * x₄))) + p(x₀ * 0.95491)...
                                      )) * -0.99927
18          6.140e+00  3.236e-02  y = (p(x₀ * 0.95487) + (sin(sin(x₂ + (x₁ * 0.67673))) + (x...
                                      ₅ * x₅))) * -0.99885
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165950_VwxoOE/hall_of_fame.csv

In [186]:
show_results(model1_p_w2)

   complexity        loss     score                          equation
5           8    9.319634  2.808845  (p(x0) + (x5 * x5)) * -0.9890003
3           5  385.373140  2.484887            (x5 * x5) * -1.1555321
4           7  154.619720  0.456622     -1.0965104 * ((x5 * x5) + x0)

best: (x5*x5 + sympy_p(x0*0.95491004))*(-0.9992701)

### Konfiguracja 2 z operatorem `p` (zakres [-15,15], σ=2)

In [187]:
model2_p_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model2_p_w2.fit(X_p_w2, y_p_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.214
3           4.540e+03  1.017e-02  y = -87.117 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.769 - (x₅ * x₅)
7           7.295e+01  4.922e-01  y = (x₀ * -1.891) - (x₅ * x₅)
8           9.026e+00  2.090e+00  y = (1.4101 - (x₅ * x₅)) - p(x₀)
9           7.362e+00  2.037e-01  y = (x₅ * (0.03147 - x₅)) - (x₀ ^ 1.4156)
10          6.478e+00  1.279e-01  y = ((0.029019 - x₅) * x₅) - p(x₀ + -0.50757)
12          6.434e+00  3.433e-03  y = ((0.029015 - x₅) * x₅) - (p(x₀ + -0.50757) - -0.22398)
13          6.370e+00  1.001e-02  y = (cos(x₀ * x₂) - (x₅ * x₅)) - p(-0.50911 + x₀)
15          5.895e+00  3.870e-02  y = (cos((x₀ * 0.4587) * x₀) - (x₅ * x₅)) - p(x₀ + -0.5091...
                                      1)
17          5.853e+00  3.613e-03  y = ((cos((x₀ * 0.4587) * x₀) - (x₅ * x₅)) - p(x₀ + -0.509...
                                      11)) - 0.22478
19          5.852e+00  4.205e-05  y = ((cos(x₀ * (x₀ * 0.45858)) - (x₅ * x₅)) - p((x₀ - 0.23...
                                      414) + -0.27527)) - 0.20987
23          5.831e+00  9.161e-04  y = (cos((x₀ * x₀) * 0.4587) - (x₅ * x₅)) - (p(x₀ + -0.509...
                                      11) - sin(cos(1.8924 - (x₀ ^ x₁))))
27          5.831e+00  1.335e-05  y = ((cos(x₀ * (x₀ * 0.4587)) - (x₅ * x₅)) - p(x₀ + -0.509...
                                      11)) - (exp((cos(x₀ * x₀) - x₅) * x₅) + 0.21041)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165953_c9ux45/hall_of_fame.csv

In [188]:
show_results(model2_p_w2)

   complexity        loss     score                        equation
3           5  195.229480  3.120413           -20.76896 - (x5 * x5)
5           8    9.025723  2.089720  (1.410093 - (x5 * x5)) - p(x0)
4           7   72.951800  0.492188   (x0 * -1.8909682) - (x5 * x5)

best: -x0**1.415573 + x5*(0.03146975 - x5)

### Konfiguracja 3 z operatorem `p` (zakres [-15,15], σ=2)

In [189]:
model3_p_w2 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model3_p_w2.fit(X_p_w2, y_p_w2)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.636e+03  0.000e+00  y = -95.209
3           4.540e+03  1.017e-02  y = -87.117 - x₀
4           4.423e+03  2.566e-02  y = -73.03 - p(x₀)
5           1.952e+02  3.120e+00  y = -20.77 - (x₅ * x₅)
7           4.434e+01  7.412e-01  y = (-3.2995 * x₀) - (x₅ * x₅)
8           9.026e+00  1.592e+00  y = (1.4101 - (x₅ * x₅)) - p(x₀)
9           7.362e+00  2.037e-01  y = ((0.031386 - x₅) * x₅) - (x₀ ^ 1.4155)
10          6.478e+00  1.279e-01  y = (x₅ * (0.029256 - x₅)) - p(x₀ + -0.50749)
12          6.434e+00  3.444e-03  y = ((x₅ * (0.029256 - x₅)) + -0.20601) - p(x₀ + -0.50749)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_165958_oTfVO9/hall_of_fame.csv

In [190]:
show_results(model3_p_w2)

   complexity        loss     score                        equation
3           5  195.229480  3.120413          -20.770227 - (x5 * x5)
5           8    9.025723  1.591743  (1.410093 - (x5 * x5)) - p(x0)
4           7   44.337110  0.741177   (-3.2994742 * x0) - (x5 * x5)

best: -x5*x5 - sympy_p(x0) + 1.410093

### 5.0 — Zakres [-15, 15], szum $\sigma=5$

In [191]:
X_p_w5, y_p_w5 = make_data_prime(-15, 15, noise_std=5)

### Konfiguracja 1 z operatorem `p` (zakres [-15,15], σ=5)

In [192]:
model1_p_w5 = PySRRegressor(
    binary_operators=["+", "*"],
    unary_operators=["cos", "exp", "sin", "p"],
    maxsize=20,
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model1_p_w5.fit(X_p_w5, y_p_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.661e+03  4.732e-04  y = x₂ + -95.696
4           4.656e+03  4.891e-04  y = sin(x₂) + -95.468
5           4.034e+02  2.446e+00  y = x₅ * (x₅ * -1.1583)
7           1.733e+02  4.226e-01  y = ((x₅ * x₅) + x₀) * -1.0994
8           3.152e+01  1.704e+00  y = ((x₅ * x₅) + p(x₀)) * -0.99112
10          2.885e+01  4.433e-02  y = (p(x₀ * 0.9549) + (x₅ * x₅)) * -1.0015
12          2.866e+01  3.227e-03  y = ((x₅ * x₅) + p((x₀ + 0.1664) * 0.94066)) * -1.0037
14          2.843e+01  4.054e-03  y = (-1.0021 + ((x₅ * x₅) + p((x₀ + 0.70009) * 0.90864))) ...
                                      * -1.0021
15          2.796e+01  1.643e-02  y = (((x₅ * x₅) + p(x₀ * 0.95491)) + cos(x₀ * 2.8787)) * -...
                                      1.002
16          2.781e+01  5.706e-03  y = sin(p(x₀ * 1.1279)) + ((p(x₀ * 0.95485) + (x₅ * x₅)) *...
                                       -0.99944)
17          2.770e+01  3.922e-03  y = -1.0021 * (cos((x₀ * 2.8505) + -0.3926) + (p(0.9549 * ...
                                      x₀) + (x₅ * x₅)))
18          2.767e+01  8.722e-04  y = sin(p(x₀ * 1.1278) + 0.36736) + (((x₅ * x₅) + p(x₀ * 0...
                                      .95476)) * -0.99945)
19          2.763e+01  1.707e-03  y = ((cos((x₀ * 2.8505) + -0.3926) + p(x₀ * 0.95477)) + (x...
                                      ₅ * (x₅ + -0.030716))) * -1.0019
20          2.760e+01  9.149e-04  y = -1.0021 * (cos(x₅) + (p(x₀ * 0.9549) + ((x₅ * x₅) + co...
                                      s((x₀ * 2.8505) + -0.3926))))
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*']"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,20
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,None
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_170000_BBjpx6/hall_of_fame.csv

In [193]:
show_results(model1_p_w5)

   complexity        loss     score                          equation
3           5  403.434700  2.445899            x5 * (x5 * -1.1582731)
5           8   31.519268  1.704235  ((x5 * x5) + p(x0)) * -0.9911184
4           7  173.267030  0.422590     ((x5 * x5) + x0) * -1.0993769

best: (x5*x5 + sympy_p(x0))*(-0.9911184)

### Konfiguracja 2 z operatorem `p` (zakres [-15,15], σ=5)

In [194]:
model2_p_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["cos", "exp", "sin", "log", "p"],
    maxsize=30,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model2_p_w5.fit(X_p_w5, y_p_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!

Expressions evaluated per second: 2.130e+05
Progress: 1134 / 1200 total iterations (94.500%)
════════════════════════════════════════════════════════════════════════════════════════════════════
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.573e+03  9.902e-03  y = -87.382 - x₀
4           4.461e+03  2.440e-02  y = -73.29 - p(x₀)
5           2.109e+02  3.051e+00  y = -21.031 - (x₅ * x₅)
7           1.171e+02  2.944e-01  y = (-12.938 - (x₅ * x₅)) - x₀
8           3.130e+01  1.319e+00  y = (1.1493 - (x₅ * x₅)) - p(x₀)
10          2.886e+01  4.069e-02  y = (-0.13245 - (x₅ * x₅)) - p(x₀ * 0.95485)
12          2.833e+01  9.228e-03  y = (0.96275 - (x₅ * x₅)) - p((x₀ * 0.8728) + 1.0815)
13          2.833e+01  6.777e-05  y = (cos(0.10371) - (x₅ * x₅)) - p(1.0815 + (x₀ * 0.8728))
14          2.819e+01  4.867e-03  y = (sin(p(x₀ + 0.41279)) - (x₅ * x₅)) - p(x₀ + -0.54904)
15          2.818e+01  1.342e-04  y = (cos(cos(p(x₀))) - (x₅ * x₅)) - p((0.8728 * x₀) + 1.08...
                                      15)
16          2.740e+01  2.825e-02  y = ((sin(p(x₀ + 0.42185)) * 2.7259) - (x₅ * x₅)) - p(x₀ +...
                                       -0.63809)
20          2.736e+01  3.809e-04  y = (sin(p(x₀ + 0.4528)) - (x₅ * x₅)) - (p(x₀ + -0.54904) ...
                                      - sin(p(x₀ + 0.4528)))
21          2.715e+01  7.512e-03  y = (sin(p(x₀ + 0.44958)) - (x₅ * x₅)) - (cos(1.2811 - (x₃...
                                       * 2.1958)) + p(x₀ + -0.50754))
22          2.705e+01  3.957e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((1.763 - x₁) * cos(x₅))
24          2.667e+01  6.957e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((-0.69522 - x₁) * (1.2452 - cos(x₅)))
26          2.662e+01  8.902e-04  y = ((sin(p(x₀ + 0.41966)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos(((-0.95484 - x₁) * (cos(x₅) - 1.2411)) - 0.44833)
28          2.632e+01  5.807e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((x₅ - ((x₂ - cos(x₄)) - (0.92154 * x₄))) - -1.2)
───────────────────────────────────────────────────────────────────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════════════════════════
Press 'q' and then <enter> to stop execution early.
───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.573e+03  9.902e-03  y = -87.382 - x₀
4           4.461e+03  2.440e-02  y = -73.29 - p(x₀)
5           2.109e+02  3.051e+00  y = -21.031 - (x₅ * x₅)
7           1.171e+02  2.944e-01  y = (-12.938 - (x₅ * x₅)) - x₀
8           3.130e+01  1.319e+00  y = (1.1493 - (x₅ * x₅)) - p(x₀)
10          2.886e+01  4.069e-02  y = (-0.13245 - (x₅ * x₅)) - p(x₀ * 0.95485)
12          2.833e+01  9.228e-03  y = (0.96275 - (x₅ * x₅)) - p((x₀ * 0.8728) + 1.0815)
13          2.833e+01  6.777e-05  y = (cos(0.10371) - (x₅ * x₅)) - p(1.0815 + (x₀ * 0.8728))
14          2.819e+01  4.867e-03  y = (sin(p(x₀ + 0.41279)) - (x₅ * x₅)) - p(x₀ + -0.54904)
15          2.818e+01  1.342e-04  y = (cos(cos(p(x₀))) - (x₅ * x₅)) - p((0.8728 * x₀) + 1.08...
                                      15)
16          2.740e+01  2.825e-02  y = ((sin(p(x₀ + 0.42185)) * 2.7259) - (x₅ * x₅)) - p(x₀ +...
                                       -0.63809)
20          2.733e+01  6.072e-04  y = (sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - (p(x₀ + -0.53416)...
                                       - sin(p(x₀ + 0.41933)))
21          2.715e+01  6.607e-03  y = (sin(p(x₀ + 0.44958)) - (x₅ * x₅)) - (cos(1.2811 - (x₃...
                                       * 2.1958)) + p(x₀ + -0.50754))
22          2.705e+01  3.957e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((1.763 - x₁) * cos(x₅))
24          2.667e+01  6.957e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((-0.69522 - x₁) * (1.2452 - cos(x₅)))
26          2.657e+01  1.895e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((x₅ - ((x₂ - cos(x₄)) - x₄)) - -1.2)
28          2.632e+01  4.802e-03  y = ((sin(p(x₀ + 0.41933)) - (x₅ * x₅)) - p(x₀ + -0.53416)...
                                      ) - cos((x₅ - ((x₂ - cos(x₄)) - (0.92154 * x₄))) - -1.2)
30          2.617e+01  2.794e-03  y = (((sin(p(x₀ + 0.41933)) + -0.18013) - (x₅ * x₅)) - p(x...
                                      ₀ + -0.53416)) - cos((x₅ - ((x₂ - cos(x₄)) - (x₄ * 0.94476...
                                      ))) - -1.4178)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Final population:
[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['cos', 'exp', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,30
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_170005_AFQaoc/hall_of_fame.csv

In [195]:
show_results(model2_p_w5)

   complexity        loss     score                         equation
3           5  210.936940  3.051560           -21.030697 - (x5 * x5)
5           8   31.301770  1.319163  (1.1492883 - (x5 * x5)) - p(x0)
4           7  117.077675  0.294361    (-12.937784 - (x5 * x5)) - x0

best: -x5*x5 - sympy_p(x0) + 1.1492883

### Konfiguracja 3 z operatorem `p` (zakres [-15,15], σ=5)

In [196]:
model3_p_w5 = PySRRegressor(
    binary_operators=["+", "*", "-", "^"],
    unary_operators=["exp", "sin", "p"],
    maxsize=15,
    constraints={"^": (-1, 1)},
    extra_sympy_mappings={"p": sympy_p},
    **default_pysr_params,
)
model3_p_w5.fit(X_p_w5, y_p_w5)

/opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env/lib/python3.10/site-packages/pysr/sr.py:2811: UserWarning: Note: it looks like you are running in Jupyter. The progress bar will be turned off.
  warnings.warn(
[ Info: Started!
[ Info: Final population:

───────────────────────────────────────────────────────────────────────────────────────────────────
Complexity  Loss       Score      Equation
1           4.667e+03  0.000e+00  y = -95.471
3           4.573e+03  9.902e-03  y = -87.377 - x₀
4           4.461e+03  2.440e-02  y = -73.29 - p(x₀)
5           2.109e+02  3.051e+00  y = -21.031 - (x₅ * x₅)
7           1.171e+02  2.944e-01  y = -12.938 - ((x₅ * x₅) + x₀)
8           3.130e+01  1.319e+00  y = (1.1496 - (x₅ * x₅)) - p(x₀)
9           2.996e+01  4.372e-02  y = ((0.037468 - x₅) * x₅) - (x₀ ^ 1.4161)
10          2.881e+01  3.939e-02  y = ((0.030153 - x₅) * x₅) - p(x₀ * 0.95489)
12          2.855e+01  4.387e-03  y = (sin(exp(x₅)) - (x₅ * x₅)) - p(x₀ * 0.95489)
13          2.792e+01  2.259e-02  y = (sin(x₀ * 1.8693) - (x₅ * x₅)) - p(x₀ * 0.95489)
15          2.772e+01  3.609e-03  y = (sin((x₀ * 0.94829) * x₀) - (x₅ * x₅)) - p(x₀ * 0.9563...
                                      9)
───────────────────────────────────────────────────────────────────────────────────────────────────

[ Info: Results saved to:

,model_selection,'best'
,binary_operators,"['+', '*', ...]"
,unary_operators,"['exp', 'sin', ...]"
,expression_spec,None
,niterations,40
,populations,30
,population_size,27
,max_evals,None
,maxsize,15
,maxdepth,None
,warmup_maxsize_by,None
,timeout_in_seconds,None
,constraints,"{'^': (-1, ...)}"
,nested_constraints,None
,elementwise_loss,None
,loss_function,None
,loss_function_expression,None
,loss_scale,'log'
,complexity_of_operators,None
,complexity_of_constants,None
,complexity_of_variables,None
,complexity_mapping,None
,parsimony,0.0
,dimensional_constraint_penalty,None
,dimensionless_constants_only,False
,use_frequency,True
,use_frequency_in_tournament,True
,adaptive_parsimony_scaling,1040.0
,alpha,3.17
,annealing,False
,early_stop_condition,None
,ncycles_per_iteration,380
,fraction_replaced,0.00036
,fraction_replaced_hof,0.0614
,weight_add_node,2.47
,weight_insert_node,0.0112
,weight_delete_node,0.87
,weight_do_nothing,0.273
,weight_mutate_constant,0.0346
,weight_mutate_operator,0.293
,weight_swap_operands,0.198
,weight_rotate_tree,4.26
,weight_randomize,0.000502
,weight_simplify,0.00209
,weight_optimize,0.0
,crossover_probability,0.0259
,skip_mutation_failures,True
,migration,True
,hof_migration,True
,topn,12
,should_simplify,True
,should_optimize_constants,True
,optimizer_algorithm,'BFGS'
,optimizer_nrestarts,2
,optimizer_f_calls_limit,None
,optimize_probability,0.14
,optimizer_iterations,8
,perturbation_factor,0.129
,probability_negate_constant,0.00743
,tournament_selection_n,15
,tournament_selection_p,0.982
,parallelism,None
,procs,None
,cluster_manager,None
,heap_size_hint_in_bytes,None
,batching,False
,batch_size,50
,fast_cycle,False
,turbo,False
,bumper,False
,precision,32
,autodiff_backend,None
,random_state,None
,deterministic,False
,warm_start,False
,verbosity,1
,update_verbosity,None
,print_precision,5
,progress,True
,logger_spec,None
,input_stream,'stdin'
,run_id,None
,output_directory,None
,temp_equation_file,False
,tempdir,None
,delete_tempfiles,True
,update,False
,output_jax_format,False
,output_torch_format,False
,extra_sympy_mappings,{'p': sympy_p}
,extra_torch_mappings,None
,extra_jax_mappings,None
,denoise,False
,select_k_features,None

  - outputs/20260516_170011_wYwJK2/hall_of_fame.csv

In [197]:
show_results(model3_p_w5)

   complexity        loss     score                         equation
3           5  210.936950  3.051560           -21.030893 - (x5 * x5)
5           8   31.301773  1.319163  (1.1496196 - (x5 * x5)) - p(x0)
4           7  117.077675  0.294361   -12.9376135 - ((x5 * x5) + x0)

best: -x5*x5 - sympy_p(x0) + 1.1496196